/*							-- DO NOT EDIT --
 * This file has been generated by smidump
 * version 0.2.17 for the scli package.
 *
 * Derived from ATM-MIB:
 *   This is the MIB Module for ATM and AAL5-related
 *   objects for managing ATM interfaces, ATM virtual
 *   links, ATM cross-connects, AAL5 entities, and
 *   and AAL5 connections.
 *
 * Revision 1998-10-19 12:00:
 *   The initial revision of this module was published
 *   as RFC 1695. Key revisions include:
 *   o  Textual Conventions and OBJECT IDENTITIES have
 *      been moved to a separate MIB module.
 *   o  Applicability of objects to PVCs, SVCs and Soft
 *      PVCs has been clarified.
 *   o  DEFVAL clauses have been added.
 *   o  The relationship of ifIndex values with different
 *      layers and sublayers related to ATM has been
 *      clarified.
 *   o  atmTrafficQosClass has been deprecated
 *      and replaced with atmServiceCategory.
 *   o  atmInterfaceCurrentMaxVpiBits and
 *      atmInterfaceCurrentMaxVciBits have been added with
 *      a description on their relationship with other
 *      objects.
 *   o  atmInterfaceAddressType and atmInterfaceAdminAddress
 *      have been deprecated and replaced by
 *      atmInterfaceSubscrAddress.
 *   o  atmInterfaceTCAlarmState has been clarified.
 *   o  atmTrafficDescrParamIndexNext has been introduced
 *      in order to provide a manager a free
 *      atmTrafficDescrParamIndex value.
 *   o  The atmTrafficFrameDiscard capability has been added.
 *   o  A connection topology type (atmVpl/VclCastType) and
 *      a call control type (atmVpl/VclConnKind) have been
 *      added.
 *   o  aal2 has been added to atmVccAalType.
 *
 * Revision 1994-06-07 22:45:
 *   The RFC1695 version of this MIB module.
 *
 * $Id$
 */

#include "atm-mib.h"

GSnmpEnum const atm_mib_enums_atmInterfaceAddressType[] = {
    { ATM_MIB_ATMINTERFACEADDRESSTYPE_PRIVATE,	"private" },
    { ATM_MIB_ATMINTERFACEADDRESSTYPE_NSAPE164,	"nsapE164" },
    { ATM_MIB_ATMINTERFACEADDRESSTYPE_NATIVEE164,	"nativeE164" },
    { ATM_MIB_ATMINTERFACEADDRESSTYPE_OTHER,	"other" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmInterfaceDs3PlcpAlarmState[] = {
    { ATM_MIB_ATMINTERFACEDS3PLCPALARMSTATE_NOALARM,	"noAlarm" },
    { ATM_MIB_ATMINTERFACEDS3PLCPALARMSTATE_RECEIVEDFARENDALARM,	"receivedFarEndAlarm" },
    { ATM_MIB_ATMINTERFACEDS3PLCPALARMSTATE_INCOMINGLOF,	"incomingLOF" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmInterfaceTCAlarmState[] = {
    { ATM_MIB_ATMINTERFACETCALARMSTATE_NOALARM,	"noAlarm" },
    { ATM_MIB_ATMINTERFACETCALARMSTATE_LCDFAILURE,	"lcdFailure" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmTrafficDescrRowStatus[] = {
    { ATM_MIB_ATMTRAFFICDESCRROWSTATUS_ACTIVE,	"active" },
    { ATM_MIB_ATMTRAFFICDESCRROWSTATUS_NOTINSERVICE,	"notInService" },
    { ATM_MIB_ATMTRAFFICDESCRROWSTATUS_NOTREADY,	"notReady" },
    { ATM_MIB_ATMTRAFFICDESCRROWSTATUS_CREATEANDGO,	"createAndGo" },
    { ATM_MIB_ATMTRAFFICDESCRROWSTATUS_CREATEANDWAIT,	"createAndWait" },
    { ATM_MIB_ATMTRAFFICDESCRROWSTATUS_DESTROY,	"destroy" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmServiceCategory[] = {
    { ATM_MIB_ATMSERVICECATEGORY_OTHER,	"other" },
    { ATM_MIB_ATMSERVICECATEGORY_CBR,	"cbr" },
    { ATM_MIB_ATMSERVICECATEGORY_RTVBR,	"rtVbr" },
    { ATM_MIB_ATMSERVICECATEGORY_NRTVBR,	"nrtVbr" },
    { ATM_MIB_ATMSERVICECATEGORY_ABR,	"abr" },
    { ATM_MIB_ATMSERVICECATEGORY_UBR,	"ubr" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmTrafficFrameDiscard[] = {
    { ATM_MIB_ATMTRAFFICFRAMEDISCARD_TRUE,	"true" },
    { ATM_MIB_ATMTRAFFICFRAMEDISCARD_FALSE,	"false" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVplAdminStatus[] = {
    { ATM_MIB_ATMVPLADMINSTATUS_UP,	"up" },
    { ATM_MIB_ATMVPLADMINSTATUS_DOWN,	"down" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVplOperStatus[] = {
    { ATM_MIB_ATMVPLOPERSTATUS_UP,	"up" },
    { ATM_MIB_ATMVPLOPERSTATUS_DOWN,	"down" },
    { ATM_MIB_ATMVPLOPERSTATUS_UNKNOWN,	"unknown" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVplRowStatus[] = {
    { ATM_MIB_ATMVPLROWSTATUS_ACTIVE,	"active" },
    { ATM_MIB_ATMVPLROWSTATUS_NOTINSERVICE,	"notInService" },
    { ATM_MIB_ATMVPLROWSTATUS_NOTREADY,	"notReady" },
    { ATM_MIB_ATMVPLROWSTATUS_CREATEANDGO,	"createAndGo" },
    { ATM_MIB_ATMVPLROWSTATUS_CREATEANDWAIT,	"createAndWait" },
    { ATM_MIB_ATMVPLROWSTATUS_DESTROY,	"destroy" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVplCastType[] = {
    { ATM_MIB_ATMVPLCASTTYPE_P2P,	"p2p" },
    { ATM_MIB_ATMVPLCASTTYPE_P2MPROOT,	"p2mpRoot" },
    { ATM_MIB_ATMVPLCASTTYPE_P2MPLEAF,	"p2mpLeaf" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVplConnKind[] = {
    { ATM_MIB_ATMVPLCONNKIND_PVC,	"pvc" },
    { ATM_MIB_ATMVPLCONNKIND_SVCINCOMING,	"svcIncoming" },
    { ATM_MIB_ATMVPLCONNKIND_SVCOUTGOING,	"svcOutgoing" },
    { ATM_MIB_ATMVPLCONNKIND_SPVCINITIATOR,	"spvcInitiator" },
    { ATM_MIB_ATMVPLCONNKIND_SPVCTARGET,	"spvcTarget" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVclAdminStatus[] = {
    { ATM_MIB_ATMVCLADMINSTATUS_UP,	"up" },
    { ATM_MIB_ATMVCLADMINSTATUS_DOWN,	"down" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVclOperStatus[] = {
    { ATM_MIB_ATMVCLOPERSTATUS_UP,	"up" },
    { ATM_MIB_ATMVCLOPERSTATUS_DOWN,	"down" },
    { ATM_MIB_ATMVCLOPERSTATUS_UNKNOWN,	"unknown" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVccAalType[] = {
    { ATM_MIB_ATMVCCAALTYPE_AAL1,	"aal1" },
    { ATM_MIB_ATMVCCAALTYPE_AAL34,	"aal34" },
    { ATM_MIB_ATMVCCAALTYPE_AAL5,	"aal5" },
    { ATM_MIB_ATMVCCAALTYPE_OTHER,	"other" },
    { ATM_MIB_ATMVCCAALTYPE_UNKNOWN,	"unknown" },
    { ATM_MIB_ATMVCCAALTYPE_AAL2,	"aal2" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVccAal5EncapsType[] = {
    { ATM_MIB_ATMVCCAAL5ENCAPSTYPE_VCMULTIPLEXROUTEDPROTOCOL,	"vcMultiplexRoutedProtocol" },
    { ATM_MIB_ATMVCCAAL5ENCAPSTYPE_VCMULTIPLEXBRIDGEDPROTOCOL8023,	"vcMultiplexBridgedProtocol8023" },
    { ATM_MIB_ATMVCCAAL5ENCAPSTYPE_VCMULTIPLEXBRIDGEDPROTOCOL8025,	"vcMultiplexBridgedProtocol8025" },
    { ATM_MIB_ATMVCCAAL5ENCAPSTYPE_VCMULTIPLEXBRIDGEDPROTOCOL8026,	"vcMultiplexBridgedProtocol8026" },
    { ATM_MIB_ATMVCCAAL5ENCAPSTYPE_VCMULTIPLEXLANEMULATION8023,	"vcMultiplexLANemulation8023" },
    { ATM_MIB_ATMVCCAAL5ENCAPSTYPE_VCMULTIPLEXLANEMULATION8025,	"vcMultiplexLANemulation8025" },
    { ATM_MIB_ATMVCCAAL5ENCAPSTYPE_LLCENCAPSULATION,	"llcEncapsulation" },
    { ATM_MIB_ATMVCCAAL5ENCAPSTYPE_MULTIPROTOCOLFRAMERELAYSSCS,	"multiprotocolFrameRelaySscs" },
    { ATM_MIB_ATMVCCAAL5ENCAPSTYPE_OTHER,	"other" },
    { ATM_MIB_ATMVCCAAL5ENCAPSTYPE_UNKNOWN,	"unknown" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVclRowStatus[] = {
    { ATM_MIB_ATMVCLROWSTATUS_ACTIVE,	"active" },
    { ATM_MIB_ATMVCLROWSTATUS_NOTINSERVICE,	"notInService" },
    { ATM_MIB_ATMVCLROWSTATUS_NOTREADY,	"notReady" },
    { ATM_MIB_ATMVCLROWSTATUS_CREATEANDGO,	"createAndGo" },
    { ATM_MIB_ATMVCLROWSTATUS_CREATEANDWAIT,	"createAndWait" },
    { ATM_MIB_ATMVCLROWSTATUS_DESTROY,	"destroy" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVclCastType[] = {
    { ATM_MIB_ATMVCLCASTTYPE_P2P,	"p2p" },
    { ATM_MIB_ATMVCLCASTTYPE_P2MPROOT,	"p2mpRoot" },
    { ATM_MIB_ATMVCLCASTTYPE_P2MPLEAF,	"p2mpLeaf" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVclConnKind[] = {
    { ATM_MIB_ATMVCLCONNKIND_PVC,	"pvc" },
    { ATM_MIB_ATMVCLCONNKIND_SVCINCOMING,	"svcIncoming" },
    { ATM_MIB_ATMVCLCONNKIND_SVCOUTGOING,	"svcOutgoing" },
    { ATM_MIB_ATMVCLCONNKIND_SPVCINITIATOR,	"spvcInitiator" },
    { ATM_MIB_ATMVCLCONNKIND_SPVCTARGET,	"spvcTarget" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVpCrossConnectAdminStatus[] = {
    { ATM_MIB_ATMVPCROSSCONNECTADMINSTATUS_UP,	"up" },
    { ATM_MIB_ATMVPCROSSCONNECTADMINSTATUS_DOWN,	"down" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVpCrossConnectL2HOperStatus[] = {
    { ATM_MIB_ATMVPCROSSCONNECTL2HOPERSTATUS_UP,	"up" },
    { ATM_MIB_ATMVPCROSSCONNECTL2HOPERSTATUS_DOWN,	"down" },
    { ATM_MIB_ATMVPCROSSCONNECTL2HOPERSTATUS_UNKNOWN,	"unknown" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVpCrossConnectH2LOperStatus[] = {
    { ATM_MIB_ATMVPCROSSCONNECTH2LOPERSTATUS_UP,	"up" },
    { ATM_MIB_ATMVPCROSSCONNECTH2LOPERSTATUS_DOWN,	"down" },
    { ATM_MIB_ATMVPCROSSCONNECTH2LOPERSTATUS_UNKNOWN,	"unknown" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVpCrossConnectRowStatus[] = {
    { ATM_MIB_ATMVPCROSSCONNECTROWSTATUS_ACTIVE,	"active" },
    { ATM_MIB_ATMVPCROSSCONNECTROWSTATUS_NOTINSERVICE,	"notInService" },
    { ATM_MIB_ATMVPCROSSCONNECTROWSTATUS_NOTREADY,	"notReady" },
    { ATM_MIB_ATMVPCROSSCONNECTROWSTATUS_CREATEANDGO,	"createAndGo" },
    { ATM_MIB_ATMVPCROSSCONNECTROWSTATUS_CREATEANDWAIT,	"createAndWait" },
    { ATM_MIB_ATMVPCROSSCONNECTROWSTATUS_DESTROY,	"destroy" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVcCrossConnectAdminStatus[] = {
    { ATM_MIB_ATMVCCROSSCONNECTADMINSTATUS_UP,	"up" },
    { ATM_MIB_ATMVCCROSSCONNECTADMINSTATUS_DOWN,	"down" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVcCrossConnectL2HOperStatus[] = {
    { ATM_MIB_ATMVCCROSSCONNECTL2HOPERSTATUS_UP,	"up" },
    { ATM_MIB_ATMVCCROSSCONNECTL2HOPERSTATUS_DOWN,	"down" },
    { ATM_MIB_ATMVCCROSSCONNECTL2HOPERSTATUS_UNKNOWN,	"unknown" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVcCrossConnectH2LOperStatus[] = {
    { ATM_MIB_ATMVCCROSSCONNECTH2LOPERSTATUS_UP,	"up" },
    { ATM_MIB_ATMVCCROSSCONNECTH2LOPERSTATUS_DOWN,	"down" },
    { ATM_MIB_ATMVCCROSSCONNECTH2LOPERSTATUS_UNKNOWN,	"unknown" },
    { 0, NULL }
};

GSnmpEnum const atm_mib_enums_atmVcCrossConnectRowStatus[] = {
    { ATM_MIB_ATMVCCROSSCONNECTROWSTATUS_ACTIVE,	"active" },
    { ATM_MIB_ATMVCCROSSCONNECTROWSTATUS_NOTINSERVICE,	"notInService" },
    { ATM_MIB_ATMVCCROSSCONNECTROWSTATUS_NOTREADY,	"notReady" },
    { ATM_MIB_ATMVCCROSSCONNECTROWSTATUS_CREATEANDGO,	"createAndGo" },
    { ATM_MIB_ATMVCCROSSCONNECTROWSTATUS_CREATEANDWAIT,	"createAndWait" },
    { ATM_MIB_ATMVCCROSSCONNECTROWSTATUS_DESTROY,	"destroy" },
    { 0, NULL }
};


typedef struct {
    guint32 const     subid;
    GSnmpVarBindType  type;
    gchar            *label;
} stls_stub_attr_t;

static void
add_attributes(GSnmpSession *s, GSList **vbl, guint32 *base, guint idx,
               stls_stub_attr_t *attributes)
{
    int i;

    for (i = 0; attributes[i].label; i++) {
        if (attributes[i].type != G_SNMP_COUNTER64 || s->version > G_SNMP_V1) {
            base[idx] = attributes[i].subid;
            g_snmp_vbl_add_null(vbl, base, idx + 1);
        }
    }
}

static int
lookup(GSnmpVarBind *vb, guint32 const *base, gsize const base_len,
	    stls_stub_attr_t *attributes, guint32 *idx)
{
    int i;

    if (vb->type == G_SNMP_ENDOFMIBVIEW
	|| (vb->type == G_SNMP_NOSUCHOBJECT)
	|| (vb->type == G_SNMP_NOSUCHINSTANCE)) {
	return -1;
    }
    
    if (memcmp(vb->id, base, base_len * sizeof(guint32)) != 0) {
	return -2;
    }

    for (i = 0; attributes[i].label; i++) {
	if (vb->id_len > base_len && vb->id[base_len] == attributes[i].subid) {
	    if (vb->type != attributes[i].type) {
		g_warning("type tag 0x%02x does not match 0x%02x (%s)",
			  vb->type, attributes[i].type, attributes[i].label);
		return -3;
	    }
	    *idx = attributes[i].subid;
	    return 0;
	}
    }
    
    return -4;
}

static stls_stub_attr_t _atmMIBObjects[] = {
    { 8, G_SNMP_INTEGER32, "atmVpCrossConnectIndexNext" },
    { 10, G_SNMP_INTEGER32, "atmVcCrossConnectIndexNext" },
    { 13, G_SNMP_INTEGER32, "atmTrafficDescrParamIndexNext" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _atmInterfaceConfEntry[] = {
    { 1, G_SNMP_INTEGER32, "atmInterfaceMaxVpcs" },
    { 2, G_SNMP_INTEGER32, "atmInterfaceMaxVccs" },
    { 3, G_SNMP_INTEGER32, "atmInterfaceConfVpcs" },
    { 4, G_SNMP_INTEGER32, "atmInterfaceConfVccs" },
    { 5, G_SNMP_INTEGER32, "atmInterfaceMaxActiveVpiBits" },
    { 6, G_SNMP_INTEGER32, "atmInterfaceMaxActiveVciBits" },
    { 7, G_SNMP_INTEGER32, "atmInterfaceIlmiVpi" },
    { 8, G_SNMP_INTEGER32, "atmInterfaceIlmiVci" },
    { 9, G_SNMP_INTEGER32, "atmInterfaceAddressType" },
    { 10, G_SNMP_OCTET_STRING, "atmInterfaceAdminAddress" },
    { 11, G_SNMP_IPADDRESS, "atmInterfaceMyNeighborIpAddress" },
    { 12, G_SNMP_OCTET_STRING, "atmInterfaceMyNeighborIfName" },
    { 13, G_SNMP_INTEGER32, "atmInterfaceCurrentMaxVpiBits" },
    { 14, G_SNMP_INTEGER32, "atmInterfaceCurrentMaxVciBits" },
    { 15, G_SNMP_OCTET_STRING, "atmInterfaceSubscrAddress" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _atmInterfaceDs3PlcpEntry[] = {
    { 1, G_SNMP_COUNTER32, "atmInterfaceDs3PlcpSEFSs" },
    { 2, G_SNMP_INTEGER32, "atmInterfaceDs3PlcpAlarmState" },
    { 3, G_SNMP_COUNTER32, "atmInterfaceDs3PlcpUASs" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _atmInterfaceTCEntry[] = {
    { 1, G_SNMP_COUNTER32, "atmInterfaceOCDEvents" },
    { 2, G_SNMP_INTEGER32, "atmInterfaceTCAlarmState" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _atmTrafficDescrParamEntry[] = {
    { 2, G_SNMP_OBJECT_ID, "atmTrafficDescrType" },
    { 3, G_SNMP_INTEGER32, "atmTrafficDescrParam1" },
    { 4, G_SNMP_INTEGER32, "atmTrafficDescrParam2" },
    { 5, G_SNMP_INTEGER32, "atmTrafficDescrParam3" },
    { 6, G_SNMP_INTEGER32, "atmTrafficDescrParam4" },
    { 7, G_SNMP_INTEGER32, "atmTrafficDescrParam5" },
    { 8, G_SNMP_INTEGER32, "atmTrafficQoSClass" },
    { 9, G_SNMP_INTEGER32, "atmTrafficDescrRowStatus" },
    { 10, G_SNMP_INTEGER32, "atmServiceCategory" },
    { 11, G_SNMP_INTEGER32, "atmTrafficFrameDiscard" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _atmVplEntry[] = {
    { 2, G_SNMP_INTEGER32, "atmVplAdminStatus" },
    { 3, G_SNMP_INTEGER32, "atmVplOperStatus" },
    { 4, G_SNMP_TIMETICKS, "atmVplLastChange" },
    { 5, G_SNMP_INTEGER32, "atmVplReceiveTrafficDescrIndex" },
    { 6, G_SNMP_INTEGER32, "atmVplTransmitTrafficDescrIndex" },
    { 7, G_SNMP_INTEGER32, "atmVplCrossConnectIdentifier" },
    { 8, G_SNMP_INTEGER32, "atmVplRowStatus" },
    { 9, G_SNMP_INTEGER32, "atmVplCastType" },
    { 10, G_SNMP_INTEGER32, "atmVplConnKind" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _atmVclEntry[] = {
    { 3, G_SNMP_INTEGER32, "atmVclAdminStatus" },
    { 4, G_SNMP_INTEGER32, "atmVclOperStatus" },
    { 5, G_SNMP_TIMETICKS, "atmVclLastChange" },
    { 6, G_SNMP_INTEGER32, "atmVclReceiveTrafficDescrIndex" },
    { 7, G_SNMP_INTEGER32, "atmVclTransmitTrafficDescrIndex" },
    { 8, G_SNMP_INTEGER32, "atmVccAalType" },
    { 9, G_SNMP_INTEGER32, "atmVccAal5CpcsTransmitSduSize" },
    { 10, G_SNMP_INTEGER32, "atmVccAal5CpcsReceiveSduSize" },
    { 11, G_SNMP_INTEGER32, "atmVccAal5EncapsType" },
    { 12, G_SNMP_INTEGER32, "atmVclCrossConnectIdentifier" },
    { 13, G_SNMP_INTEGER32, "atmVclRowStatus" },
    { 14, G_SNMP_INTEGER32, "atmVclCastType" },
    { 15, G_SNMP_INTEGER32, "atmVclConnKind" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _atmVpCrossConnectEntry[] = {
    { 6, G_SNMP_INTEGER32, "atmVpCrossConnectAdminStatus" },
    { 7, G_SNMP_INTEGER32, "atmVpCrossConnectL2HOperStatus" },
    { 8, G_SNMP_INTEGER32, "atmVpCrossConnectH2LOperStatus" },
    { 9, G_SNMP_TIMETICKS, "atmVpCrossConnectL2HLastChange" },
    { 10, G_SNMP_TIMETICKS, "atmVpCrossConnectH2LLastChange" },
    { 11, G_SNMP_INTEGER32, "atmVpCrossConnectRowStatus" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _atmVcCrossConnectEntry[] = {
    { 8, G_SNMP_INTEGER32, "atmVcCrossConnectAdminStatus" },
    { 9, G_SNMP_INTEGER32, "atmVcCrossConnectL2HOperStatus" },
    { 10, G_SNMP_INTEGER32, "atmVcCrossConnectH2LOperStatus" },
    { 11, G_SNMP_TIMETICKS, "atmVcCrossConnectL2HLastChange" },
    { 12, G_SNMP_TIMETICKS, "atmVcCrossConnectH2LLastChange" },
    { 13, G_SNMP_INTEGER32, "atmVcCrossConnectRowStatus" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _aal5VccEntry[] = {
    { 3, G_SNMP_COUNTER32, "aal5VccCrcErrors" },
    { 4, G_SNMP_COUNTER32, "aal5VccSarTimeOuts" },
    { 5, G_SNMP_COUNTER32, "aal5VccOverSizedSDUs" },
    { 0, 0, NULL }
};


atm_mib_atmMIBObjects_t *
atm_mib_new_atmMIBObjects()
{
    atm_mib_atmMIBObjects_t *atmMIBObjects;

    atmMIBObjects = (atm_mib_atmMIBObjects_t *) g_malloc0(sizeof(atm_mib_atmMIBObjects_t) + sizeof(gpointer));
    return atmMIBObjects;
}

static atm_mib_atmMIBObjects_t *
assign_atmMIBObjects(GSList *vbl)
{
    GSList *elem;
    atm_mib_atmMIBObjects_t *atmMIBObjects;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 37, 1};

    atmMIBObjects = atm_mib_new_atmMIBObjects();
    if (! atmMIBObjects) {
        return NULL;
    }

    p = (char *) atmMIBObjects + sizeof(atm_mib_atmMIBObjects_t);
    * (GSList **) p = vbl;

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _atmMIBObjects, &idx) < 0) continue;

        switch (idx) {
        case 8:
            atmMIBObjects->atmVpCrossConnectIndexNext = &(vb->syntax.i32[0]);
            break;
        case 10:
            atmMIBObjects->atmVcCrossConnectIndexNext = &(vb->syntax.i32[0]);
            break;
        case 13:
            atmMIBObjects->atmTrafficDescrParamIndexNext = &(vb->syntax.i32[0]);
            break;
        };
    }

    return atmMIBObjects;
}

int
atm_mib_get_atmMIBObjects(GSnmpSession *s, atm_mib_atmMIBObjects_t **atmMIBObjects)
{
    GSList *in = NULL, *out = NULL;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 37, 1, 0};

    *atmMIBObjects = NULL;

    add_attributes(s, &in, base, 8, _atmMIBObjects);

    out = g_snmp_session_sync_getnext(s, in);
    g_snmp_vbl_free(in);
    if (! out) {
        return -2;
    }

    *atmMIBObjects = assign_atmMIBObjects(out);

    return 0;
}

void
atm_mib_free_atmMIBObjects(atm_mib_atmMIBObjects_t *atmMIBObjects)
{
    GSList *vbl;
    char *p;

    if (atmMIBObjects) {
        p = (char *) atmMIBObjects + sizeof(atm_mib_atmMIBObjects_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(atmMIBObjects);
    }
}

atm_mib_atmInterfaceConfEntry_t *
atm_mib_new_atmInterfaceConfEntry()
{
    atm_mib_atmInterfaceConfEntry_t *atmInterfaceConfEntry;

    atmInterfaceConfEntry = (atm_mib_atmInterfaceConfEntry_t *) g_malloc0(sizeof(atm_mib_atmInterfaceConfEntry_t) + sizeof(gpointer));
    return atmInterfaceConfEntry;
}

static int
unpack_atmInterfaceConfEntry(GSnmpVarBind *vb, atm_mib_atmInterfaceConfEntry_t *atmInterfaceConfEntry)
{
    int idx = 11;

    if (vb->id_len < idx) return -1;
    atmInterfaceConfEntry->ifIndex = vb->id[idx++];
    if (vb->id_len > idx) return -1;
    return 0;
}

static atm_mib_atmInterfaceConfEntry_t *
assign_atmInterfaceConfEntry(GSList *vbl)
{
    GSList *elem;
    atm_mib_atmInterfaceConfEntry_t *atmInterfaceConfEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 37, 1, 2, 1};

    atmInterfaceConfEntry = atm_mib_new_atmInterfaceConfEntry();
    if (! atmInterfaceConfEntry) {
        return NULL;
    }

    p = (char *) atmInterfaceConfEntry + sizeof(atm_mib_atmInterfaceConfEntry_t);
    * (GSList **) p = vbl;

    if (unpack_atmInterfaceConfEntry((GSnmpVarBind *) vbl->data, atmInterfaceConfEntry) < 0) {
        g_warning("illegal atmInterfaceConfEntry instance identifier");
        g_free(atmInterfaceConfEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _atmInterfaceConfEntry, &idx) < 0) continue;

        switch (idx) {
        case 1:
            atmInterfaceConfEntry->atmInterfaceMaxVpcs = &(vb->syntax.i32[0]);
            break;
        case 2:
            atmInterfaceConfEntry->atmInterfaceMaxVccs = &(vb->syntax.i32[0]);
            break;
        case 3:
            atmInterfaceConfEntry->atmInterfaceConfVpcs = &(vb->syntax.i32[0]);
            break;
        case 4:
            atmInterfaceConfEntry->atmInterfaceConfVccs = &(vb->syntax.i32[0]);
            break;
        case 5:
            atmInterfaceConfEntry->atmInterfaceMaxActiveVpiBits = &(vb->syntax.i32[0]);
            break;
        case 6:
            atmInterfaceConfEntry->atmInterfaceMaxActiveVciBits = &(vb->syntax.i32[0]);
            break;
        case 7:
            atmInterfaceConfEntry->atmInterfaceIlmiVpi = &(vb->syntax.i32[0]);
            break;
        case 8:
            atmInterfaceConfEntry->atmInterfaceIlmiVci = &(vb->syntax.i32[0]);
            break;
        case 9:
            atmInterfaceConfEntry->atmInterfaceAddressType = &(vb->syntax.i32[0]);
            break;
        case 10:
            atmInterfaceConfEntry->_atmInterfaceAdminAddressLength = vb->syntax_len;
            atmInterfaceConfEntry->atmInterfaceAdminAddress = vb->syntax.uc;
            break;
        case 11:
            atmInterfaceConfEntry->atmInterfaceMyNeighborIpAddress = vb->syntax.uc;
            break;
        case 12:
            atmInterfaceConfEntry->_atmInterfaceMyNeighborIfNameLength = vb->syntax_len;
            atmInterfaceConfEntry->atmInterfaceMyNeighborIfName = vb->syntax.uc;
            break;
        case 13:
            atmInterfaceConfEntry->atmInterfaceCurrentMaxVpiBits = &(vb->syntax.i32[0]);
            break;
        case 14:
            atmInterfaceConfEntry->atmInterfaceCurrentMaxVciBits = &(vb->syntax.i32[0]);
            break;
        case 15:
            atmInterfaceConfEntry->_atmInterfaceSubscrAddressLength = vb->syntax_len;
            atmInterfaceConfEntry->atmInterfaceSubscrAddress = vb->syntax.uc;
            break;
        };
    }

    return atmInterfaceConfEntry;
}

int
atm_mib_get_atmInterfaceConfTable(GSnmpSession *s, atm_mib_atmInterfaceConfEntry_t ***atmInterfaceConfEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 37, 1, 2, 1, 0};

    *atmInterfaceConfEntry = NULL;

    add_attributes(s, &in, base, 10, _atmInterfaceConfEntry);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *atmInterfaceConfEntry = (atm_mib_atmInterfaceConfEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(atm_mib_atmInterfaceConfEntry_t *));
    if (! *atmInterfaceConfEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*atmInterfaceConfEntry)[i] = assign_atmInterfaceConfEntry(row->data);
    }

    return 0;
}

void
atm_mib_free_atmInterfaceConfEntry(atm_mib_atmInterfaceConfEntry_t *atmInterfaceConfEntry)
{
    GSList *vbl;
    char *p;

    if (atmInterfaceConfEntry) {
        p = (char *) atmInterfaceConfEntry + sizeof(atm_mib_atmInterfaceConfEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(atmInterfaceConfEntry);
    }
}

void
atm_mib_free_atmInterfaceConfTable(atm_mib_atmInterfaceConfEntry_t **atmInterfaceConfEntry)
{
    int i;

    if (atmInterfaceConfEntry) {
        for (i = 0; atmInterfaceConfEntry[i]; i++) {
            atm_mib_free_atmInterfaceConfEntry(atmInterfaceConfEntry[i]);
        }
        g_free(atmInterfaceConfEntry);
    }
}

atm_mib_atmInterfaceDs3PlcpEntry_t *
atm_mib_new_atmInterfaceDs3PlcpEntry()
{
    atm_mib_atmInterfaceDs3PlcpEntry_t *atmInterfaceDs3PlcpEntry;

    atmInterfaceDs3PlcpEntry = (atm_mib_atmInterfaceDs3PlcpEntry_t *) g_malloc0(sizeof(atm_mib_atmInterfaceDs3PlcpEntry_t) + sizeof(gpointer));
    return atmInterfaceDs3PlcpEntry;
}

static int
unpack_atmInterfaceDs3PlcpEntry(GSnmpVarBind *vb, atm_mib_atmInterfaceDs3PlcpEntry_t *atmInterfaceDs3PlcpEntry)
{
    int idx = 11;

    if (vb->id_len < idx) return -1;
    atmInterfaceDs3PlcpEntry->ifIndex = vb->id[idx++];
    if (vb->id_len > idx) return -1;
    return 0;
}

static atm_mib_atmInterfaceDs3PlcpEntry_t *
assign_atmInterfaceDs3PlcpEntry(GSList *vbl)
{
    GSList *elem;
    atm_mib_atmInterfaceDs3PlcpEntry_t *atmInterfaceDs3PlcpEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 37, 1, 3, 1};

    atmInterfaceDs3PlcpEntry = atm_mib_new_atmInterfaceDs3PlcpEntry();
    if (! atmInterfaceDs3PlcpEntry) {
        return NULL;
    }

    p = (char *) atmInterfaceDs3PlcpEntry + sizeof(atm_mib_atmInterfaceDs3PlcpEntry_t);
    * (GSList **) p = vbl;

    if (unpack_atmInterfaceDs3PlcpEntry((GSnmpVarBind *) vbl->data, atmInterfaceDs3PlcpEntry) < 0) {
        g_warning("illegal atmInterfaceDs3PlcpEntry instance identifier");
        g_free(atmInterfaceDs3PlcpEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _atmInterfaceDs3PlcpEntry, &idx) < 0) continue;

        switch (idx) {
        case 1:
            atmInterfaceDs3PlcpEntry->atmInterfaceDs3PlcpSEFSs = &(vb->syntax.ui32[0]);
            break;
        case 2:
            atmInterfaceDs3PlcpEntry->atmInterfaceDs3PlcpAlarmState = &(vb->syntax.i32[0]);
            break;
        case 3:
            atmInterfaceDs3PlcpEntry->atmInterfaceDs3PlcpUASs = &(vb->syntax.ui32[0]);
            break;
        };
    }

    return atmInterfaceDs3PlcpEntry;
}

int
atm_mib_get_atmInterfaceDs3PlcpTable(GSnmpSession *s, atm_mib_atmInterfaceDs3PlcpEntry_t ***atmInterfaceDs3PlcpEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 37, 1, 3, 1, 0};

    *atmInterfaceDs3PlcpEntry = NULL;

    add_attributes(s, &in, base, 10, _atmInterfaceDs3PlcpEntry);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *atmInterfaceDs3PlcpEntry = (atm_mib_atmInterfaceDs3PlcpEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(atm_mib_atmInterfaceDs3PlcpEntry_t *));
    if (! *atmInterfaceDs3PlcpEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*atmInterfaceDs3PlcpEntry)[i] = assign_atmInterfaceDs3PlcpEntry(row->data);
    }

    return 0;
}

void
atm_mib_free_atmInterfaceDs3PlcpEntry(atm_mib_atmInterfaceDs3PlcpEntry_t *atmInterfaceDs3PlcpEntry)
{
    GSList *vbl;
    char *p;

    if (atmInterfaceDs3PlcpEntry) {
        p = (char *) atmInterfaceDs3PlcpEntry + sizeof(atm_mib_atmInterfaceDs3PlcpEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(atmInterfaceDs3PlcpEntry);
    }
}

void
atm_mib_free_atmInterfaceDs3PlcpTable(atm_mib_atmInterfaceDs3PlcpEntry_t **atmInterfaceDs3PlcpEntry)
{
    int i;

    if (atmInterfaceDs3PlcpEntry) {
        for (i = 0; atmInterfaceDs3PlcpEntry[i]; i++) {
            atm_mib_free_atmInterfaceDs3PlcpEntry(atmInterfaceDs3PlcpEntry[i]);
        }
        g_free(atmInterfaceDs3PlcpEntry);
    }
}

atm_mib_atmInterfaceTCEntry_t *
atm_mib_new_atmInterfaceTCEntry()
{
    atm_mib_atmInterfaceTCEntry_t *atmInterfaceTCEntry;

    atmInterfaceTCEntry = (atm_mib_atmInterfaceTCEntry_t *) g_malloc0(sizeof(atm_mib_atmInterfaceTCEntry_t) + sizeof(gpointer));
    return atmInterfaceTCEntry;
}

static int
unpack_atmInterfaceTCEntry(GSnmpVarBind *vb, atm_mib_atmInterfaceTCEntry_t *atmInterfaceTCEntry)
{
    int idx = 11;

    if (vb->id_len < idx) return -1;
    atmInterfaceTCEntry->ifIndex = vb->id[idx++];
    if (vb->id_len > idx) return -1;
    return 0;
}

static atm_mib_atmInterfaceTCEntry_t *
assign_atmInterfaceTCEntry(GSList *vbl)
{
    GSList *elem;
    atm_mib_atmInterfaceTCEntry_t *atmInterfaceTCEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 37, 1, 4, 1};

    atmInterfaceTCEntry = atm_mib_new_atmInterfaceTCEntry();
    if (! atmInterfaceTCEntry) {
        return NULL;
    }

    p = (char *) atmInterfaceTCEntry + sizeof(atm_mib_atmInterfaceTCEntry_t);
    * (GSList **) p = vbl;

    if (unpack_atmInterfaceTCEntry((GSnmpVarBind *) vbl->data, atmInterfaceTCEntry) < 0) {
        g_warning("illegal atmInterfaceTCEntry instance identifier");
        g_free(atmInterfaceTCEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _atmInterfaceTCEntry, &idx) < 0) continue;

        switch (idx) {
        case 1:
            atmInterfaceTCEntry->atmInterfaceOCDEvents = &(vb->syntax.ui32[0]);
            break;
        case 2:
            atmInterfaceTCEntry->atmInterfaceTCAlarmState = &(vb->syntax.i32[0]);
            break;
        };
    }

    return atmInterfaceTCEntry;
}

int
atm_mib_get_atmInterfaceTCTable(GSnmpSession *s, atm_mib_atmInterfaceTCEntry_t ***atmInterfaceTCEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 37, 1, 4, 1, 0};

    *atmInterfaceTCEntry = NULL;

    add_attributes(s, &in, base, 10, _atmInterfaceTCEntry);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *atmInterfaceTCEntry = (atm_mib_atmInterfaceTCEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(atm_mib_atmInterfaceTCEntry_t *));
    if (! *atmInterfaceTCEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*atmInterfaceTCEntry)[i] = assign_atmInterfaceTCEntry(row->data);
    }

    return 0;
}

void
atm_mib_free_atmInterfaceTCEntry(atm_mib_atmInterfaceTCEntry_t *atmInterfaceTCEntry)
{
    GSList *vbl;
    char *p;

    if (atmInterfaceTCEntry) {
        p = (char *) atmInterfaceTCEntry + sizeof(atm_mib_atmInterfaceTCEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(atmInterfaceTCEntry);
    }
}

void
atm_mib_free_atmInterfaceTCTable(atm_mib_atmInterfaceTCEntry_t **atmInterfaceTCEntry)
{
    int i;

    if (atmInterfaceTCEntry) {
        for (i = 0; atmInterfaceTCEntry[i]; i++) {
            atm_mib_free_atmInterfaceTCEntry(atmInterfaceTCEntry[i]);
        }
        g_free(atmInterfaceTCEntry);
    }
}

atm_mib_atmTrafficDescrParamEntry_t *
atm_mib_new_atmTrafficDescrParamEntry()
{
    atm_mib_atmTrafficDescrParamEntry_t *atmTrafficDescrParamEntry;

    atmTrafficDescrParamEntry = (atm_mib_atmTrafficDescrParamEntry_t *) g_malloc0(sizeof(atm_mib_atmTrafficDescrParamEntry_t) + sizeof(gpointer));
    return atmTrafficDescrParamEntry;
}

static int
unpack_atmTrafficDescrParamEntry(GSnmpVarBind *vb, atm_mib_atmTrafficDescrParamEntry_t *atmTrafficDescrParamEntry)
{
    int idx = 11;

    if (vb->id_len < idx) return -1;
    atmTrafficDescrParamEntry->atmTrafficDescrParamIndex = vb->id[idx++];
    if (vb->id_len > idx) return -1;
    return 0;
}

static atm_mib_atmTrafficDescrParamEntry_t *
assign_atmTrafficDescrParamEntry(GSList *vbl)
{
    GSList *elem;
    atm_mib_atmTrafficDescrParamEntry_t *atmTrafficDescrParamEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 37, 1, 5, 1};

    atmTrafficDescrParamEntry = atm_mib_new_atmTrafficDescrParamEntry();
    if (! atmTrafficDescrParamEntry) {
        return NULL;
    }

    p = (char *) atmTrafficDescrParamEntry + sizeof(atm_mib_atmTrafficDescrParamEntry_t);
    * (GSList **) p = vbl;

    if (unpack_atmTrafficDescrParamEntry((GSnmpVarBind *) vbl->data, atmTrafficDescrParamEntry) < 0) {
        g_warning("illegal atmTrafficDescrParamEntry instance identifier");
        g_free(atmTrafficDescrParamEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _atmTrafficDescrParamEntry, &idx) < 0) continue;

        switch (idx) {
        case 2:
            atmTrafficDescrParamEntry->_atmTrafficDescrTypeLength = vb->syntax_len / sizeof(guint32);
            atmTrafficDescrParamEntry->atmTrafficDescrType = vb->syntax.ui32;
            break;
        case 3:
            atmTrafficDescrParamEntry->atmTrafficDescrParam1 = &(vb->syntax.i32[0]);
            break;
        case 4:
            atmTrafficDescrParamEntry->atmTrafficDescrParam2 = &(vb->syntax.i32[0]);
            break;
        case 5:
            atmTrafficDescrParamEntry->atmTrafficDescrParam3 = &(vb->syntax.i32[0]);
            break;
        case 6:
            atmTrafficDescrParamEntry->atmTrafficDescrParam4 = &(vb->syntax.i32[0]);
            break;
        case 7:
            atmTrafficDescrParamEntry->atmTrafficDescrParam5 = &(vb->syntax.i32[0]);
            break;
        case 8:
            atmTrafficDescrParamEntry->atmTrafficQoSClass = &(vb->syntax.i32[0]);
            break;
        case 9:
            atmTrafficDescrParamEntry->atmTrafficDescrRowStatus = &(vb->syntax.i32[0]);
            break;
        case 10:
            atmTrafficDescrParamEntry->atmServiceCategory = &(vb->syntax.i32[0]);
            break;
        case 11:
            atmTrafficDescrParamEntry->atmTrafficFrameDiscard = &(vb->syntax.i32[0]);
            break;
        };
    }

    return atmTrafficDescrParamEntry;
}

int
atm_mib_get_atmTrafficDescrParamTable(GSnmpSession *s, atm_mib_atmTrafficDescrParamEntry_t ***atmTrafficDescrParamEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 37, 1, 5, 1, 0};

    *atmTrafficDescrParamEntry = NULL;

    add_attributes(s, &in, base, 10, _atmTrafficDescrParamEntry);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *atmTrafficDescrParamEntry = (atm_mib_atmTrafficDescrParamEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(atm_mib_atmTrafficDescrParamEntry_t *));
    if (! *atmTrafficDescrParamEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*atmTrafficDescrParamEntry)[i] = assign_atmTrafficDescrParamEntry(row->data);
    }

    return 0;
}

void
atm_mib_free_atmTrafficDescrParamEntry(atm_mib_atmTrafficDescrParamEntry_t *atmTrafficDescrParamEntry)
{
    GSList *vbl;
    char *p;

    if (atmTrafficDescrParamEntry) {
        p = (char *) atmTrafficDescrParamEntry + sizeof(atm_mib_atmTrafficDescrParamEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(atmTrafficDescrParamEntry);
    }
}

void
atm_mib_free_atmTrafficDescrParamTable(atm_mib_atmTrafficDescrParamEntry_t **atmTrafficDescrParamEntry)
{
    int i;

    if (atmTrafficDescrParamEntry) {
        for (i = 0; atmTrafficDescrParamEntry[i]; i++) {
            atm_mib_free_atmTrafficDescrParamEntry(atmTrafficDescrParamEntry[i]);
        }
        g_free(atmTrafficDescrParamEntry);
    }
}

atm_mib_atmVplEntry_t *
atm_mib_new_atmVplEntry()
{
    atm_mib_atmVplEntry_t *atmVplEntry;

    atmVplEntry = (atm_mib_atmVplEntry_t *) g_malloc0(sizeof(atm_mib_atmVplEntry_t) + sizeof(gpointer));
    return atmVplEntry;
}

static int
unpack_atmVplEntry(GSnmpVarBind *vb, atm_mib_atmVplEntry_t *atmVplEntry)
{
    int idx = 11;

    if (vb->id_len < idx) return -1;
    atmVplEntry->ifIndex = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    atmVplEntry->atmVplVpi = vb->id[idx++];
    if (vb->id_len > idx) return -1;
    return 0;
}

static atm_mib_atmVplEntry_t *
assign_atmVplEntry(GSList *vbl)
{
    GSList *elem;
    atm_mib_atmVplEntry_t *atmVplEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 37, 1, 6, 1};

    atmVplEntry = atm_mib_new_atmVplEntry();
    if (! atmVplEntry) {
        return NULL;
    }

    p = (char *) atmVplEntry + sizeof(atm_mib_atmVplEntry_t);
    * (GSList **) p = vbl;

    if (unpack_atmVplEntry((GSnmpVarBind *) vbl->data, atmVplEntry) < 0) {
        g_warning("illegal atmVplEntry instance identifier");
        g_free(atmVplEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _atmVplEntry, &idx) < 0) continue;

        switch (idx) {
        case 2:
            atmVplEntry->atmVplAdminStatus = &(vb->syntax.i32[0]);
            break;
        case 3:
            atmVplEntry->atmVplOperStatus = &(vb->syntax.i32[0]);
            break;
        case 4:
            atmVplEntry->atmVplLastChange = &(vb->syntax.ui32[0]);
            break;
        case 5:
            atmVplEntry->atmVplReceiveTrafficDescrIndex = &(vb->syntax.i32[0]);
            break;
        case 6:
            atmVplEntry->atmVplTransmitTrafficDescrIndex = &(vb->syntax.i32[0]);
            break;
        case 7:
            atmVplEntry->atmVplCrossConnectIdentifier = &(vb->syntax.i32[0]);
            break;
        case 8:
            atmVplEntry->atmVplRowStatus = &(vb->syntax.i32[0]);
            break;
        case 9:
            atmVplEntry->atmVplCastType = &(vb->syntax.i32[0]);
            break;
        case 10:
            atmVplEntry->atmVplConnKind = &(vb->syntax.i32[0]);
            break;
        };
    }

    return atmVplEntry;
}

int
atm_mib_get_atmVplTable(GSnmpSession *s, atm_mib_atmVplEntry_t ***atmVplEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 37, 1, 6, 1, 0};

    *atmVplEntry = NULL;

    add_attributes(s, &in, base, 10, _atmVplEntry);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *atmVplEntry = (atm_mib_atmVplEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(atm_mib_atmVplEntry_t *));
    if (! *atmVplEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*atmVplEntry)[i] = assign_atmVplEntry(row->data);
    }

    return 0;
}

void
atm_mib_free_atmVplEntry(atm_mib_atmVplEntry_t *atmVplEntry)
{
    GSList *vbl;
    char *p;

    if (atmVplEntry) {
        p = (char *) atmVplEntry + sizeof(atm_mib_atmVplEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(atmVplEntry);
    }
}

void
atm_mib_free_atmVplTable(atm_mib_atmVplEntry_t **atmVplEntry)
{
    int i;

    if (atmVplEntry) {
        for (i = 0; atmVplEntry[i]; i++) {
            atm_mib_free_atmVplEntry(atmVplEntry[i]);
        }
        g_free(atmVplEntry);
    }
}

atm_mib_atmVclEntry_t *
atm_mib_new_atmVclEntry()
{
    atm_mib_atmVclEntry_t *atmVclEntry;

    atmVclEntry = (atm_mib_atmVclEntry_t *) g_malloc0(sizeof(atm_mib_atmVclEntry_t) + sizeof(gpointer));
    return atmVclEntry;
}

static int
unpack_atmVclEntry(GSnmpVarBind *vb, atm_mib_atmVclEntry_t *atmVclEntry)
{
    int idx = 11;

    if (vb->id_len < idx) return -1;
    atmVclEntry->ifIndex = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    atmVclEntry->atmVclVpi = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    atmVclEntry->atmVclVci = vb->id[idx++];
    if (vb->id_len > idx) return -1;
    return 0;
}

static atm_mib_atmVclEntry_t *
assign_atmVclEntry(GSList *vbl)
{
    GSList *elem;
    atm_mib_atmVclEntry_t *atmVclEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 37, 1, 7, 1};

    atmVclEntry = atm_mib_new_atmVclEntry();
    if (! atmVclEntry) {
        return NULL;
    }

    p = (char *) atmVclEntry + sizeof(atm_mib_atmVclEntry_t);
    * (GSList **) p = vbl;

    if (unpack_atmVclEntry((GSnmpVarBind *) vbl->data, atmVclEntry) < 0) {
        g_warning("illegal atmVclEntry instance identifier");
        g_free(atmVclEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _atmVclEntry, &idx) < 0) continue;

        switch (idx) {
        case 3:
            atmVclEntry->atmVclAdminStatus = &(vb->syntax.i32[0]);
            break;
        case 4:
            atmVclEntry->atmVclOperStatus = &(vb->syntax.i32[0]);
            break;
        case 5:
            atmVclEntry->atmVclLastChange = &(vb->syntax.ui32[0]);
            break;
        case 6:
            atmVclEntry->atmVclReceiveTrafficDescrIndex = &(vb->syntax.i32[0]);
            break;
        case 7:
            atmVclEntry->atmVclTransmitTrafficDescrIndex = &(vb->syntax.i32[0]);
            break;
        case 8:
            atmVclEntry->atmVccAalType = &(vb->syntax.i32[0]);
            break;
        case 9:
            atmVclEntry->atmVccAal5CpcsTransmitSduSize = &(vb->syntax.i32[0]);
            break;
        case 10:
            atmVclEntry->atmVccAal5CpcsReceiveSduSize = &(vb->syntax.i32[0]);
            break;
        case 11:
            atmVclEntry->atmVccAal5EncapsType = &(vb->syntax.i32[0]);
            break;
        case 12:
            atmVclEntry->atmVclCrossConnectIdentifier = &(vb->syntax.i32[0]);
            break;
        case 13:
            atmVclEntry->atmVclRowStatus = &(vb->syntax.i32[0]);
            break;
        case 14:
            atmVclEntry->atmVclCastType = &(vb->syntax.i32[0]);
            break;
        case 15:
            atmVclEntry->atmVclConnKind = &(vb->syntax.i32[0]);
            break;
        };
    }

    return atmVclEntry;
}

int
atm_mib_get_atmVclTable(GSnmpSession *s, atm_mib_atmVclEntry_t ***atmVclEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 37, 1, 7, 1, 0};

    *atmVclEntry = NULL;

    add_attributes(s, &in, base, 10, _atmVclEntry);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *atmVclEntry = (atm_mib_atmVclEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(atm_mib_atmVclEntry_t *));
    if (! *atmVclEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*atmVclEntry)[i] = assign_atmVclEntry(row->data);
    }

    return 0;
}

void
atm_mib_free_atmVclEntry(atm_mib_atmVclEntry_t *atmVclEntry)
{
    GSList *vbl;
    char *p;

    if (atmVclEntry) {
        p = (char *) atmVclEntry + sizeof(atm_mib_atmVclEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(atmVclEntry);
    }
}

void
atm_mib_free_atmVclTable(atm_mib_atmVclEntry_t **atmVclEntry)
{
    int i;

    if (atmVclEntry) {
        for (i = 0; atmVclEntry[i]; i++) {
            atm_mib_free_atmVclEntry(atmVclEntry[i]);
        }
        g_free(atmVclEntry);
    }
}

atm_mib_atmVpCrossConnectEntry_t *
atm_mib_new_atmVpCrossConnectEntry()
{
    atm_mib_atmVpCrossConnectEntry_t *atmVpCrossConnectEntry;

    atmVpCrossConnectEntry = (atm_mib_atmVpCrossConnectEntry_t *) g_malloc0(sizeof(atm_mib_atmVpCrossConnectEntry_t) + sizeof(gpointer));
    return atmVpCrossConnectEntry;
}

static int
unpack_atmVpCrossConnectEntry(GSnmpVarBind *vb, atm_mib_atmVpCrossConnectEntry_t *atmVpCrossConnectEntry)
{
    int idx = 11;

    if (vb->id_len < idx) return -1;
    atmVpCrossConnectEntry->atmVpCrossConnectIndex = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    atmVpCrossConnectEntry->atmVpCrossConnectLowIfIndex = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    atmVpCrossConnectEntry->atmVpCrossConnectLowVpi = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    atmVpCrossConnectEntry->atmVpCrossConnectHighIfIndex = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    atmVpCrossConnectEntry->atmVpCrossConnectHighVpi = vb->id[idx++];
    if (vb->id_len > idx) return -1;
    return 0;
}

static atm_mib_atmVpCrossConnectEntry_t *
assign_atmVpCrossConnectEntry(GSList *vbl)
{
    GSList *elem;
    atm_mib_atmVpCrossConnectEntry_t *atmVpCrossConnectEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 37, 1, 9, 1};

    atmVpCrossConnectEntry = atm_mib_new_atmVpCrossConnectEntry();
    if (! atmVpCrossConnectEntry) {
        return NULL;
    }

    p = (char *) atmVpCrossConnectEntry + sizeof(atm_mib_atmVpCrossConnectEntry_t);
    * (GSList **) p = vbl;

    if (unpack_atmVpCrossConnectEntry((GSnmpVarBind *) vbl->data, atmVpCrossConnectEntry) < 0) {
        g_warning("illegal atmVpCrossConnectEntry instance identifier");
        g_free(atmVpCrossConnectEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _atmVpCrossConnectEntry, &idx) < 0) continue;

        switch (idx) {
        case 6:
            atmVpCrossConnectEntry->atmVpCrossConnectAdminStatus = &(vb->syntax.i32[0]);
            break;
        case 7:
            atmVpCrossConnectEntry->atmVpCrossConnectL2HOperStatus = &(vb->syntax.i32[0]);
            break;
        case 8:
            atmVpCrossConnectEntry->atmVpCrossConnectH2LOperStatus = &(vb->syntax.i32[0]);
            break;
        case 9:
            atmVpCrossConnectEntry->atmVpCrossConnectL2HLastChange = &(vb->syntax.ui32[0]);
            break;
        case 10:
            atmVpCrossConnectEntry->atmVpCrossConnectH2LLastChange = &(vb->syntax.ui32[0]);
            break;
        case 11:
            atmVpCrossConnectEntry->atmVpCrossConnectRowStatus = &(vb->syntax.i32[0]);
            break;
        };
    }

    return atmVpCrossConnectEntry;
}

int
atm_mib_get_atmVpCrossConnectTable(GSnmpSession *s, atm_mib_atmVpCrossConnectEntry_t ***atmVpCrossConnectEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 37, 1, 9, 1, 0};

    *atmVpCrossConnectEntry = NULL;

    add_attributes(s, &in, base, 10, _atmVpCrossConnectEntry);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *atmVpCrossConnectEntry = (atm_mib_atmVpCrossConnectEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(atm_mib_atmVpCrossConnectEntry_t *));
    if (! *atmVpCrossConnectEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*atmVpCrossConnectEntry)[i] = assign_atmVpCrossConnectEntry(row->data);
    }

    return 0;
}

void
atm_mib_free_atmVpCrossConnectEntry(atm_mib_atmVpCrossConnectEntry_t *atmVpCrossConnectEntry)
{
    GSList *vbl;
    char *p;

    if (atmVpCrossConnectEntry) {
        p = (char *) atmVpCrossConnectEntry + sizeof(atm_mib_atmVpCrossConnectEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(atmVpCrossConnectEntry);
    }
}

void
atm_mib_free_atmVpCrossConnectTable(atm_mib_atmVpCrossConnectEntry_t **atmVpCrossConnectEntry)
{
    int i;

    if (atmVpCrossConnectEntry) {
        for (i = 0; atmVpCrossConnectEntry[i]; i++) {
            atm_mib_free_atmVpCrossConnectEntry(atmVpCrossConnectEntry[i]);
        }
        g_free(atmVpCrossConnectEntry);
    }
}

atm_mib_atmVcCrossConnectEntry_t *
atm_mib_new_atmVcCrossConnectEntry()
{
    atm_mib_atmVcCrossConnectEntry_t *atmVcCrossConnectEntry;

    atmVcCrossConnectEntry = (atm_mib_atmVcCrossConnectEntry_t *) g_malloc0(sizeof(atm_mib_atmVcCrossConnectEntry_t) + sizeof(gpointer));
    return atmVcCrossConnectEntry;
}

static int
unpack_atmVcCrossConnectEntry(GSnmpVarBind *vb, atm_mib_atmVcCrossConnectEntry_t *atmVcCrossConnectEntry)
{
    int idx = 11;

    if (vb->id_len < idx) return -1;
    atmVcCrossConnectEntry->atmVcCrossConnectIndex = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    atmVcCrossConnectEntry->atmVcCrossConnectLowIfIndex = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    atmVcCrossConnectEntry->atmVcCrossConnectLowVpi = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    atmVcCrossConnectEntry->atmVcCrossConnectLowVci = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    atmVcCrossConnectEntry->atmVcCrossConnectHighIfIndex = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    atmVcCrossConnectEntry->atmVcCrossConnectHighVpi = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    atmVcCrossConnectEntry->atmVcCrossConnectHighVci = vb->id[idx++];
    if (vb->id_len > idx) return -1;
    return 0;
}

static atm_mib_atmVcCrossConnectEntry_t *
assign_atmVcCrossConnectEntry(GSList *vbl)
{
    GSList *elem;
    atm_mib_atmVcCrossConnectEntry_t *atmVcCrossConnectEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 37, 1, 11, 1};

    atmVcCrossConnectEntry = atm_mib_new_atmVcCrossConnectEntry();
    if (! atmVcCrossConnectEntry) {
        return NULL;
    }

    p = (char *) atmVcCrossConnectEntry + sizeof(atm_mib_atmVcCrossConnectEntry_t);
    * (GSList **) p = vbl;

    if (unpack_atmVcCrossConnectEntry((GSnmpVarBind *) vbl->data, atmVcCrossConnectEntry) < 0) {
        g_warning("illegal atmVcCrossConnectEntry instance identifier");
        g_free(atmVcCrossConnectEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _atmVcCrossConnectEntry, &idx) < 0) continue;

        switch (idx) {
        case 8:
            atmVcCrossConnectEntry->atmVcCrossConnectAdminStatus = &(vb->syntax.i32[0]);
            break;
        case 9:
            atmVcCrossConnectEntry->atmVcCrossConnectL2HOperStatus = &(vb->syntax.i32[0]);
            break;
        case 10:
            atmVcCrossConnectEntry->atmVcCrossConnectH2LOperStatus = &(vb->syntax.i32[0]);
            break;
        case 11:
            atmVcCrossConnectEntry->atmVcCrossConnectL2HLastChange = &(vb->syntax.ui32[0]);
            break;
        case 12:
            atmVcCrossConnectEntry->atmVcCrossConnectH2LLastChange = &(vb->syntax.ui32[0]);
            break;
        case 13:
            atmVcCrossConnectEntry->atmVcCrossConnectRowStatus = &(vb->syntax.i32[0]);
            break;
        };
    }

    return atmVcCrossConnectEntry;
}

int
atm_mib_get_atmVcCrossConnectTable(GSnmpSession *s, atm_mib_atmVcCrossConnectEntry_t ***atmVcCrossConnectEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 37, 1, 11, 1, 0};

    *atmVcCrossConnectEntry = NULL;

    add_attributes(s, &in, base, 10, _atmVcCrossConnectEntry);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *atmVcCrossConnectEntry = (atm_mib_atmVcCrossConnectEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(atm_mib_atmVcCrossConnectEntry_t *));
    if (! *atmVcCrossConnectEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*atmVcCrossConnectEntry)[i] = assign_atmVcCrossConnectEntry(row->data);
    }

    return 0;
}

void
atm_mib_free_atmVcCrossConnectEntry(atm_mib_atmVcCrossConnectEntry_t *atmVcCrossConnectEntry)
{
    GSList *vbl;
    char *p;

    if (atmVcCrossConnectEntry) {
        p = (char *) atmVcCrossConnectEntry + sizeof(atm_mib_atmVcCrossConnectEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(atmVcCrossConnectEntry);
    }
}

void
atm_mib_free_atmVcCrossConnectTable(atm_mib_atmVcCrossConnectEntry_t **atmVcCrossConnectEntry)
{
    int i;

    if (atmVcCrossConnectEntry) {
        for (i = 0; atmVcCrossConnectEntry[i]; i++) {
            atm_mib_free_atmVcCrossConnectEntry(atmVcCrossConnectEntry[i]);
        }
        g_free(atmVcCrossConnectEntry);
    }
}

atm_mib_aal5VccEntry_t *
atm_mib_new_aal5VccEntry()
{
    atm_mib_aal5VccEntry_t *aal5VccEntry;

    aal5VccEntry = (atm_mib_aal5VccEntry_t *) g_malloc0(sizeof(atm_mib_aal5VccEntry_t) + sizeof(gpointer));
    return aal5VccEntry;
}

static int
unpack_aal5VccEntry(GSnmpVarBind *vb, atm_mib_aal5VccEntry_t *aal5VccEntry)
{
    int idx = 11;

    if (vb->id_len < idx) return -1;
    aal5VccEntry->ifIndex = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    aal5VccEntry->aal5VccVpi = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    aal5VccEntry->aal5VccVci = vb->id[idx++];
    if (vb->id_len > idx) return -1;
    return 0;
}

static atm_mib_aal5VccEntry_t *
assign_aal5VccEntry(GSList *vbl)
{
    GSList *elem;
    atm_mib_aal5VccEntry_t *aal5VccEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 37, 1, 12, 1};

    aal5VccEntry = atm_mib_new_aal5VccEntry();
    if (! aal5VccEntry) {
        return NULL;
    }

    p = (char *) aal5VccEntry + sizeof(atm_mib_aal5VccEntry_t);
    * (GSList **) p = vbl;

    if (unpack_aal5VccEntry((GSnmpVarBind *) vbl->data, aal5VccEntry) < 0) {
        g_warning("illegal aal5VccEntry instance identifier");
        g_free(aal5VccEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _aal5VccEntry, &idx) < 0) continue;

        switch (idx) {
        case 3:
            aal5VccEntry->aal5VccCrcErrors = &(vb->syntax.ui32[0]);
            break;
        case 4:
            aal5VccEntry->aal5VccSarTimeOuts = &(vb->syntax.ui32[0]);
            break;
        case 5:
            aal5VccEntry->aal5VccOverSizedSDUs = &(vb->syntax.ui32[0]);
            break;
        };
    }

    return aal5VccEntry;
}

int
atm_mib_get_aal5VccTable(GSnmpSession *s, atm_mib_aal5VccEntry_t ***aal5VccEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 37, 1, 12, 1, 0};

    *aal5VccEntry = NULL;

    add_attributes(s, &in, base, 10, _aal5VccEntry);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *aal5VccEntry = (atm_mib_aal5VccEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(atm_mib_aal5VccEntry_t *));
    if (! *aal5VccEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*aal5VccEntry)[i] = assign_aal5VccEntry(row->data);
    }

    return 0;
}

void
atm_mib_free_aal5VccEntry(atm_mib_aal5VccEntry_t *aal5VccEntry)
{
    GSList *vbl;
    char *p;

    if (aal5VccEntry) {
        p = (char *) aal5VccEntry + sizeof(atm_mib_aal5VccEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(aal5VccEntry);
    }
}

void
atm_mib_free_aal5VccTable(atm_mib_aal5VccEntry_t **aal5VccEntry)
{
    int i;

    if (aal5VccEntry) {
        for (i = 0; aal5VccEntry[i]; i++) {
            atm_mib_free_aal5VccEntry(aal5VccEntry[i]);
        }
        g_free(aal5VccEntry);
    }
}


