/*							-- DO NOT EDIT --
 * This file has been generated by smidump
 * version 0.2.17 for the scli package.
 *
 * Derived from BRIDGE-MIB:
 *
 * $Id$
 */

#include "bridge-mib.h"

GSnmpEnum const bridge_mib_enums_dot1dBaseType[] = {
    { BRIDGE_MIB_DOT1DBASETYPE_UNKNOWN,	"unknown" },
    { BRIDGE_MIB_DOT1DBASETYPE_TRANSPARENT_ONLY,	"transparent-only" },
    { BRIDGE_MIB_DOT1DBASETYPE_SOURCEROUTE_ONLY,	"sourceroute-only" },
    { BRIDGE_MIB_DOT1DBASETYPE_SRT,	"srt" },
    { 0, NULL }
};

GSnmpEnum const bridge_mib_enums_dot1dStpProtocolSpecification[] = {
    { BRIDGE_MIB_DOT1DSTPPROTOCOLSPECIFICATION_UNKNOWN,	"unknown" },
    { BRIDGE_MIB_DOT1DSTPPROTOCOLSPECIFICATION_DECLB100,	"decLb100" },
    { BRIDGE_MIB_DOT1DSTPPROTOCOLSPECIFICATION_IEEE8021D,	"ieee8021d" },
    { 0, NULL }
};

GSnmpEnum const bridge_mib_enums_dot1dStpPortState[] = {
    { BRIDGE_MIB_DOT1DSTPPORTSTATE_DISABLED,	"disabled" },
    { BRIDGE_MIB_DOT1DSTPPORTSTATE_BLOCKING,	"blocking" },
    { BRIDGE_MIB_DOT1DSTPPORTSTATE_LISTENING,	"listening" },
    { BRIDGE_MIB_DOT1DSTPPORTSTATE_LEARNING,	"learning" },
    { BRIDGE_MIB_DOT1DSTPPORTSTATE_FORWARDING,	"forwarding" },
    { BRIDGE_MIB_DOT1DSTPPORTSTATE_BROKEN,	"broken" },
    { 0, NULL }
};

GSnmpEnum const bridge_mib_enums_dot1dStpPortEnable[] = {
    { BRIDGE_MIB_DOT1DSTPPORTENABLE_ENABLED,	"enabled" },
    { BRIDGE_MIB_DOT1DSTPPORTENABLE_DISABLED,	"disabled" },
    { 0, NULL }
};

GSnmpEnum const bridge_mib_enums_dot1dTpFdbStatus[] = {
    { BRIDGE_MIB_DOT1DTPFDBSTATUS_OTHER,	"other" },
    { BRIDGE_MIB_DOT1DTPFDBSTATUS_INVALID,	"invalid" },
    { BRIDGE_MIB_DOT1DTPFDBSTATUS_LEARNED,	"learned" },
    { BRIDGE_MIB_DOT1DTPFDBSTATUS_SELF,	"self" },
    { BRIDGE_MIB_DOT1DTPFDBSTATUS_MGMT,	"mgmt" },
    { 0, NULL }
};

GSnmpEnum const bridge_mib_enums_dot1dStaticStatus[] = {
    { BRIDGE_MIB_DOT1DSTATICSTATUS_OTHER,	"other" },
    { BRIDGE_MIB_DOT1DSTATICSTATUS_INVALID,	"invalid" },
    { BRIDGE_MIB_DOT1DSTATICSTATUS_PERMANENT,	"permanent" },
    { BRIDGE_MIB_DOT1DSTATICSTATUS_DELETEONRESET,	"deleteOnReset" },
    { BRIDGE_MIB_DOT1DSTATICSTATUS_DELETEONTIMEOUT,	"deleteOnTimeout" },
    { 0, NULL }
};


typedef struct {
    guint32 const     subid;
    GSnmpVarBindType  type;
    gchar            *label;
} stls_stub_attr_t;

static void
add_attributes(GSnmpSession *s, GSList **vbl, guint32 *base, guint idx,
               stls_stub_attr_t *attributes)
{
    int i;

    for (i = 0; attributes[i].label; i++) {
        if (attributes[i].type != G_SNMP_COUNTER64 || s->version > G_SNMP_V1) {
            base[idx] = attributes[i].subid;
            g_snmp_vbl_add_null(vbl, base, idx + 1);
        }
    }
}

static int
lookup(GSnmpVarBind *vb, guint32 const *base, gsize const base_len,
	    stls_stub_attr_t *attributes, guint32 *idx)
{
    int i;

    if (vb->type == G_SNMP_ENDOFMIBVIEW
	|| (vb->type == G_SNMP_NOSUCHOBJECT)
	|| (vb->type == G_SNMP_NOSUCHINSTANCE)) {
	return -1;
    }
    
    if (memcmp(vb->id, base, base_len * sizeof(guint32)) != 0) {
	return -2;
    }

    for (i = 0; attributes[i].label; i++) {
	if (vb->id_len > base_len && vb->id[base_len] == attributes[i].subid) {
	    if (vb->type != attributes[i].type) {
		g_warning("type tag 0x%02x does not match 0x%02x (%s)",
			  vb->type, attributes[i].type, attributes[i].label);
		return -3;
	    }
	    *idx = attributes[i].subid;
	    return 0;
	}
    }
    
    return -4;
}

static stls_stub_attr_t _dot1dBase[] = {
    { 1, G_SNMP_OCTET_STRING, "dot1dBaseBridgeAddress" },
    { 2, G_SNMP_INTEGER32, "dot1dBaseNumPorts" },
    { 3, G_SNMP_INTEGER32, "dot1dBaseType" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _dot1dBasePortEntry[] = {
    { 2, G_SNMP_INTEGER32, "dot1dBasePortIfIndex" },
    { 3, G_SNMP_OBJECT_ID, "dot1dBasePortCircuit" },
    { 4, G_SNMP_COUNTER32, "dot1dBasePortDelayExceededDiscards" },
    { 5, G_SNMP_COUNTER32, "dot1dBasePortMtuExceededDiscards" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _dot1dStp[] = {
    { 1, G_SNMP_INTEGER32, "dot1dStpProtocolSpecification" },
    { 2, G_SNMP_INTEGER32, "dot1dStpPriority" },
    { 3, G_SNMP_TIMETICKS, "dot1dStpTimeSinceTopologyChange" },
    { 4, G_SNMP_COUNTER32, "dot1dStpTopChanges" },
    { 5, G_SNMP_OCTET_STRING, "dot1dStpDesignatedRoot" },
    { 6, G_SNMP_INTEGER32, "dot1dStpRootCost" },
    { 7, G_SNMP_INTEGER32, "dot1dStpRootPort" },
    { 8, G_SNMP_INTEGER32, "dot1dStpMaxAge" },
    { 9, G_SNMP_INTEGER32, "dot1dStpHelloTime" },
    { 10, G_SNMP_INTEGER32, "dot1dStpHoldTime" },
    { 11, G_SNMP_INTEGER32, "dot1dStpForwardDelay" },
    { 12, G_SNMP_INTEGER32, "dot1dStpBridgeMaxAge" },
    { 13, G_SNMP_INTEGER32, "dot1dStpBridgeHelloTime" },
    { 14, G_SNMP_INTEGER32, "dot1dStpBridgeForwardDelay" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _dot1dStpPortEntry[] = {
    { 2, G_SNMP_INTEGER32, "dot1dStpPortPriority" },
    { 3, G_SNMP_INTEGER32, "dot1dStpPortState" },
    { 4, G_SNMP_INTEGER32, "dot1dStpPortEnable" },
    { 5, G_SNMP_INTEGER32, "dot1dStpPortPathCost" },
    { 6, G_SNMP_OCTET_STRING, "dot1dStpPortDesignatedRoot" },
    { 7, G_SNMP_INTEGER32, "dot1dStpPortDesignatedCost" },
    { 8, G_SNMP_OCTET_STRING, "dot1dStpPortDesignatedBridge" },
    { 9, G_SNMP_OCTET_STRING, "dot1dStpPortDesignatedPort" },
    { 10, G_SNMP_COUNTER32, "dot1dStpPortForwardTransitions" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _dot1dTp[] = {
    { 1, G_SNMP_COUNTER32, "dot1dTpLearnedEntryDiscards" },
    { 2, G_SNMP_INTEGER32, "dot1dTpAgingTime" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _dot1dTpFdbEntry[] = {
    { 2, G_SNMP_INTEGER32, "dot1dTpFdbPort" },
    { 3, G_SNMP_INTEGER32, "dot1dTpFdbStatus" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _dot1dTpPortEntry[] = {
    { 2, G_SNMP_INTEGER32, "dot1dTpPortMaxInfo" },
    { 3, G_SNMP_COUNTER32, "dot1dTpPortInFrames" },
    { 4, G_SNMP_COUNTER32, "dot1dTpPortOutFrames" },
    { 5, G_SNMP_COUNTER32, "dot1dTpPortInDiscards" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _dot1dStaticEntry[] = {
    { 3, G_SNMP_OCTET_STRING, "dot1dStaticAllowedToGoTo" },
    { 4, G_SNMP_INTEGER32, "dot1dStaticStatus" },
    { 0, 0, NULL }
};


bridge_mib_dot1dBase_t *
bridge_mib_new_dot1dBase()
{
    bridge_mib_dot1dBase_t *dot1dBase;

    dot1dBase = (bridge_mib_dot1dBase_t *) g_malloc0(sizeof(bridge_mib_dot1dBase_t) + sizeof(gpointer));
    return dot1dBase;
}

static bridge_mib_dot1dBase_t *
assign_dot1dBase(GSList *vbl)
{
    GSList *elem;
    bridge_mib_dot1dBase_t *dot1dBase;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 17, 1};

    dot1dBase = bridge_mib_new_dot1dBase();
    if (! dot1dBase) {
        return NULL;
    }

    p = (char *) dot1dBase + sizeof(bridge_mib_dot1dBase_t);
    * (GSList **) p = vbl;

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _dot1dBase, &idx) < 0) continue;

        switch (idx) {
        case 1:
            dot1dBase->dot1dBaseBridgeAddress = vb->syntax.uc;
            break;
        case 2:
            dot1dBase->dot1dBaseNumPorts = &(vb->syntax.i32[0]);
            break;
        case 3:
            dot1dBase->dot1dBaseType = &(vb->syntax.i32[0]);
            break;
        };
    }

    return dot1dBase;
}

int
bridge_mib_get_dot1dBase(GSnmpSession *s, bridge_mib_dot1dBase_t **dot1dBase)
{
    GSList *in = NULL, *out = NULL;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 17, 1, 0};

    *dot1dBase = NULL;

    add_attributes(s, &in, base, 8, _dot1dBase);

    out = g_snmp_session_sync_getnext(s, in);
    g_snmp_vbl_free(in);
    if (! out) {
        return -2;
    }

    *dot1dBase = assign_dot1dBase(out);

    return 0;
}

void
bridge_mib_free_dot1dBase(bridge_mib_dot1dBase_t *dot1dBase)
{
    GSList *vbl;
    char *p;

    if (dot1dBase) {
        p = (char *) dot1dBase + sizeof(bridge_mib_dot1dBase_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(dot1dBase);
    }
}

bridge_mib_dot1dBasePortEntry_t *
bridge_mib_new_dot1dBasePortEntry()
{
    bridge_mib_dot1dBasePortEntry_t *dot1dBasePortEntry;

    dot1dBasePortEntry = (bridge_mib_dot1dBasePortEntry_t *) g_malloc0(sizeof(bridge_mib_dot1dBasePortEntry_t) + sizeof(gpointer));
    return dot1dBasePortEntry;
}

static int
unpack_dot1dBasePortEntry(GSnmpVarBind *vb, bridge_mib_dot1dBasePortEntry_t *dot1dBasePortEntry)
{
    int idx = 11;

    if (vb->id_len < idx) return -1;
    dot1dBasePortEntry->dot1dBasePort = vb->id[idx++];
    if (vb->id_len > idx) return -1;
    return 0;
}

static bridge_mib_dot1dBasePortEntry_t *
assign_dot1dBasePortEntry(GSList *vbl)
{
    GSList *elem;
    bridge_mib_dot1dBasePortEntry_t *dot1dBasePortEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 17, 1, 4, 1};

    dot1dBasePortEntry = bridge_mib_new_dot1dBasePortEntry();
    if (! dot1dBasePortEntry) {
        return NULL;
    }

    p = (char *) dot1dBasePortEntry + sizeof(bridge_mib_dot1dBasePortEntry_t);
    * (GSList **) p = vbl;

    if (unpack_dot1dBasePortEntry((GSnmpVarBind *) vbl->data, dot1dBasePortEntry) < 0) {
        g_warning("illegal dot1dBasePortEntry instance identifier");
        g_free(dot1dBasePortEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _dot1dBasePortEntry, &idx) < 0) continue;

        switch (idx) {
        case 2:
            dot1dBasePortEntry->dot1dBasePortIfIndex = &(vb->syntax.i32[0]);
            break;
        case 3:
            dot1dBasePortEntry->_dot1dBasePortCircuitLength = vb->syntax_len / sizeof(guint32);
            dot1dBasePortEntry->dot1dBasePortCircuit = vb->syntax.ui32;
            break;
        case 4:
            dot1dBasePortEntry->dot1dBasePortDelayExceededDiscards = &(vb->syntax.ui32[0]);
            break;
        case 5:
            dot1dBasePortEntry->dot1dBasePortMtuExceededDiscards = &(vb->syntax.ui32[0]);
            break;
        };
    }

    return dot1dBasePortEntry;
}

int
bridge_mib_get_dot1dBasePortTable(GSnmpSession *s, bridge_mib_dot1dBasePortEntry_t ***dot1dBasePortEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 17, 1, 4, 1, 0};

    *dot1dBasePortEntry = NULL;

    add_attributes(s, &in, base, 10, _dot1dBasePortEntry);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *dot1dBasePortEntry = (bridge_mib_dot1dBasePortEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(bridge_mib_dot1dBasePortEntry_t *));
    if (! *dot1dBasePortEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*dot1dBasePortEntry)[i] = assign_dot1dBasePortEntry(row->data);
    }

    return 0;
}

void
bridge_mib_free_dot1dBasePortEntry(bridge_mib_dot1dBasePortEntry_t *dot1dBasePortEntry)
{
    GSList *vbl;
    char *p;

    if (dot1dBasePortEntry) {
        p = (char *) dot1dBasePortEntry + sizeof(bridge_mib_dot1dBasePortEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(dot1dBasePortEntry);
    }
}

void
bridge_mib_free_dot1dBasePortTable(bridge_mib_dot1dBasePortEntry_t **dot1dBasePortEntry)
{
    int i;

    if (dot1dBasePortEntry) {
        for (i = 0; dot1dBasePortEntry[i]; i++) {
            bridge_mib_free_dot1dBasePortEntry(dot1dBasePortEntry[i]);
        }
        g_free(dot1dBasePortEntry);
    }
}

bridge_mib_dot1dStp_t *
bridge_mib_new_dot1dStp()
{
    bridge_mib_dot1dStp_t *dot1dStp;

    dot1dStp = (bridge_mib_dot1dStp_t *) g_malloc0(sizeof(bridge_mib_dot1dStp_t) + sizeof(gpointer));
    return dot1dStp;
}

static bridge_mib_dot1dStp_t *
assign_dot1dStp(GSList *vbl)
{
    GSList *elem;
    bridge_mib_dot1dStp_t *dot1dStp;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 17, 2};

    dot1dStp = bridge_mib_new_dot1dStp();
    if (! dot1dStp) {
        return NULL;
    }

    p = (char *) dot1dStp + sizeof(bridge_mib_dot1dStp_t);
    * (GSList **) p = vbl;

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _dot1dStp, &idx) < 0) continue;

        switch (idx) {
        case 1:
            dot1dStp->dot1dStpProtocolSpecification = &(vb->syntax.i32[0]);
            break;
        case 2:
            dot1dStp->dot1dStpPriority = &(vb->syntax.i32[0]);
            break;
        case 3:
            dot1dStp->dot1dStpTimeSinceTopologyChange = &(vb->syntax.ui32[0]);
            break;
        case 4:
            dot1dStp->dot1dStpTopChanges = &(vb->syntax.ui32[0]);
            break;
        case 5:
            dot1dStp->dot1dStpDesignatedRoot = vb->syntax.uc;
            break;
        case 6:
            dot1dStp->dot1dStpRootCost = &(vb->syntax.i32[0]);
            break;
        case 7:
            dot1dStp->dot1dStpRootPort = &(vb->syntax.i32[0]);
            break;
        case 8:
            dot1dStp->dot1dStpMaxAge = &(vb->syntax.i32[0]);
            break;
        case 9:
            dot1dStp->dot1dStpHelloTime = &(vb->syntax.i32[0]);
            break;
        case 10:
            dot1dStp->dot1dStpHoldTime = &(vb->syntax.i32[0]);
            break;
        case 11:
            dot1dStp->dot1dStpForwardDelay = &(vb->syntax.i32[0]);
            break;
        case 12:
            dot1dStp->dot1dStpBridgeMaxAge = &(vb->syntax.i32[0]);
            break;
        case 13:
            dot1dStp->dot1dStpBridgeHelloTime = &(vb->syntax.i32[0]);
            break;
        case 14:
            dot1dStp->dot1dStpBridgeForwardDelay = &(vb->syntax.i32[0]);
            break;
        };
    }

    return dot1dStp;
}

int
bridge_mib_get_dot1dStp(GSnmpSession *s, bridge_mib_dot1dStp_t **dot1dStp)
{
    GSList *in = NULL, *out = NULL;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 17, 2, 0};

    *dot1dStp = NULL;

    add_attributes(s, &in, base, 8, _dot1dStp);

    out = g_snmp_session_sync_getnext(s, in);
    g_snmp_vbl_free(in);
    if (! out) {
        return -2;
    }

    *dot1dStp = assign_dot1dStp(out);

    return 0;
}

int
bridge_mib_set_dot1dStp(GSnmpSession *s, bridge_mib_dot1dStp_t *dot1dStp)
{
    GSList *in = NULL, *out = NULL;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 17, 2, 0, 0};

    if (dot1dStp->dot1dStpPriority) {
        base[8] = 2;
        g_snmp_vbl_add(&in, base, sizeof(base)/sizeof(guint32),
                       G_SNMP_INTEGER32,
                       dot1dStp->dot1dStpPriority,
                       0);
    }
    if (dot1dStp->dot1dStpBridgeMaxAge) {
        base[8] = 12;
        g_snmp_vbl_add(&in, base, sizeof(base)/sizeof(guint32),
                       G_SNMP_INTEGER32,
                       dot1dStp->dot1dStpBridgeMaxAge,
                       0);
    }
    if (dot1dStp->dot1dStpBridgeHelloTime) {
        base[8] = 13;
        g_snmp_vbl_add(&in, base, sizeof(base)/sizeof(guint32),
                       G_SNMP_INTEGER32,
                       dot1dStp->dot1dStpBridgeHelloTime,
                       0);
    }
    if (dot1dStp->dot1dStpBridgeForwardDelay) {
        base[8] = 14;
        g_snmp_vbl_add(&in, base, sizeof(base)/sizeof(guint32),
                       G_SNMP_INTEGER32,
                       dot1dStp->dot1dStpBridgeForwardDelay,
                       0);
    }

    out = g_snmp_session_sync_set(s, in);
    g_snmp_vbl_free(in);
    if (! out) {
        return -2;
    }
    g_snmp_vbl_free(out);

    return 0;
}

void
bridge_mib_free_dot1dStp(bridge_mib_dot1dStp_t *dot1dStp)
{
    GSList *vbl;
    char *p;

    if (dot1dStp) {
        p = (char *) dot1dStp + sizeof(bridge_mib_dot1dStp_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(dot1dStp);
    }
}

bridge_mib_dot1dStpPortEntry_t *
bridge_mib_new_dot1dStpPortEntry()
{
    bridge_mib_dot1dStpPortEntry_t *dot1dStpPortEntry;

    dot1dStpPortEntry = (bridge_mib_dot1dStpPortEntry_t *) g_malloc0(sizeof(bridge_mib_dot1dStpPortEntry_t) + sizeof(gpointer));
    return dot1dStpPortEntry;
}

static int
unpack_dot1dStpPortEntry(GSnmpVarBind *vb, bridge_mib_dot1dStpPortEntry_t *dot1dStpPortEntry)
{
    int idx = 11;

    if (vb->id_len < idx) return -1;
    dot1dStpPortEntry->dot1dStpPort = vb->id[idx++];
    if (vb->id_len > idx) return -1;
    return 0;
}

static bridge_mib_dot1dStpPortEntry_t *
assign_dot1dStpPortEntry(GSList *vbl)
{
    GSList *elem;
    bridge_mib_dot1dStpPortEntry_t *dot1dStpPortEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 17, 2, 15, 1};

    dot1dStpPortEntry = bridge_mib_new_dot1dStpPortEntry();
    if (! dot1dStpPortEntry) {
        return NULL;
    }

    p = (char *) dot1dStpPortEntry + sizeof(bridge_mib_dot1dStpPortEntry_t);
    * (GSList **) p = vbl;

    if (unpack_dot1dStpPortEntry((GSnmpVarBind *) vbl->data, dot1dStpPortEntry) < 0) {
        g_warning("illegal dot1dStpPortEntry instance identifier");
        g_free(dot1dStpPortEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _dot1dStpPortEntry, &idx) < 0) continue;

        switch (idx) {
        case 2:
            dot1dStpPortEntry->dot1dStpPortPriority = &(vb->syntax.i32[0]);
            break;
        case 3:
            dot1dStpPortEntry->dot1dStpPortState = &(vb->syntax.i32[0]);
            break;
        case 4:
            dot1dStpPortEntry->dot1dStpPortEnable = &(vb->syntax.i32[0]);
            break;
        case 5:
            dot1dStpPortEntry->dot1dStpPortPathCost = &(vb->syntax.i32[0]);
            break;
        case 6:
            dot1dStpPortEntry->dot1dStpPortDesignatedRoot = vb->syntax.uc;
            break;
        case 7:
            dot1dStpPortEntry->dot1dStpPortDesignatedCost = &(vb->syntax.i32[0]);
            break;
        case 8:
            dot1dStpPortEntry->dot1dStpPortDesignatedBridge = vb->syntax.uc;
            break;
        case 9:
            dot1dStpPortEntry->dot1dStpPortDesignatedPort = vb->syntax.uc;
            break;
        case 10:
            dot1dStpPortEntry->dot1dStpPortForwardTransitions = &(vb->syntax.ui32[0]);
            break;
        };
    }

    return dot1dStpPortEntry;
}

int
bridge_mib_get_dot1dStpPortTable(GSnmpSession *s, bridge_mib_dot1dStpPortEntry_t ***dot1dStpPortEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 17, 2, 15, 1, 0};

    *dot1dStpPortEntry = NULL;

    add_attributes(s, &in, base, 10, _dot1dStpPortEntry);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *dot1dStpPortEntry = (bridge_mib_dot1dStpPortEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(bridge_mib_dot1dStpPortEntry_t *));
    if (! *dot1dStpPortEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*dot1dStpPortEntry)[i] = assign_dot1dStpPortEntry(row->data);
    }

    return 0;
}

void
bridge_mib_free_dot1dStpPortEntry(bridge_mib_dot1dStpPortEntry_t *dot1dStpPortEntry)
{
    GSList *vbl;
    char *p;

    if (dot1dStpPortEntry) {
        p = (char *) dot1dStpPortEntry + sizeof(bridge_mib_dot1dStpPortEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(dot1dStpPortEntry);
    }
}

void
bridge_mib_free_dot1dStpPortTable(bridge_mib_dot1dStpPortEntry_t **dot1dStpPortEntry)
{
    int i;

    if (dot1dStpPortEntry) {
        for (i = 0; dot1dStpPortEntry[i]; i++) {
            bridge_mib_free_dot1dStpPortEntry(dot1dStpPortEntry[i]);
        }
        g_free(dot1dStpPortEntry);
    }
}

bridge_mib_dot1dTp_t *
bridge_mib_new_dot1dTp()
{
    bridge_mib_dot1dTp_t *dot1dTp;

    dot1dTp = (bridge_mib_dot1dTp_t *) g_malloc0(sizeof(bridge_mib_dot1dTp_t) + sizeof(gpointer));
    return dot1dTp;
}

static bridge_mib_dot1dTp_t *
assign_dot1dTp(GSList *vbl)
{
    GSList *elem;
    bridge_mib_dot1dTp_t *dot1dTp;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 17, 4};

    dot1dTp = bridge_mib_new_dot1dTp();
    if (! dot1dTp) {
        return NULL;
    }

    p = (char *) dot1dTp + sizeof(bridge_mib_dot1dTp_t);
    * (GSList **) p = vbl;

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _dot1dTp, &idx) < 0) continue;

        switch (idx) {
        case 1:
            dot1dTp->dot1dTpLearnedEntryDiscards = &(vb->syntax.ui32[0]);
            break;
        case 2:
            dot1dTp->dot1dTpAgingTime = &(vb->syntax.i32[0]);
            break;
        };
    }

    return dot1dTp;
}

int
bridge_mib_get_dot1dTp(GSnmpSession *s, bridge_mib_dot1dTp_t **dot1dTp)
{
    GSList *in = NULL, *out = NULL;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 17, 4, 0};

    *dot1dTp = NULL;

    add_attributes(s, &in, base, 8, _dot1dTp);

    out = g_snmp_session_sync_getnext(s, in);
    g_snmp_vbl_free(in);
    if (! out) {
        return -2;
    }

    *dot1dTp = assign_dot1dTp(out);

    return 0;
}

int
bridge_mib_set_dot1dTp(GSnmpSession *s, bridge_mib_dot1dTp_t *dot1dTp)
{
    GSList *in = NULL, *out = NULL;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 17, 4, 0, 0};

    if (dot1dTp->dot1dTpAgingTime) {
        base[8] = 2;
        g_snmp_vbl_add(&in, base, sizeof(base)/sizeof(guint32),
                       G_SNMP_INTEGER32,
                       dot1dTp->dot1dTpAgingTime,
                       0);
    }

    out = g_snmp_session_sync_set(s, in);
    g_snmp_vbl_free(in);
    if (! out) {
        return -2;
    }
    g_snmp_vbl_free(out);

    return 0;
}

void
bridge_mib_free_dot1dTp(bridge_mib_dot1dTp_t *dot1dTp)
{
    GSList *vbl;
    char *p;

    if (dot1dTp) {
        p = (char *) dot1dTp + sizeof(bridge_mib_dot1dTp_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(dot1dTp);
    }
}

bridge_mib_dot1dTpFdbEntry_t *
bridge_mib_new_dot1dTpFdbEntry()
{
    bridge_mib_dot1dTpFdbEntry_t *dot1dTpFdbEntry;

    dot1dTpFdbEntry = (bridge_mib_dot1dTpFdbEntry_t *) g_malloc0(sizeof(bridge_mib_dot1dTpFdbEntry_t) + sizeof(gpointer));
    return dot1dTpFdbEntry;
}

static int
unpack_dot1dTpFdbEntry(GSnmpVarBind *vb, bridge_mib_dot1dTpFdbEntry_t *dot1dTpFdbEntry)
{
    int i, len, idx = 11;

    len = 6;
    if (vb->id_len < idx + len) return -1;
    for (i = 0; i < len; i++) {
        dot1dTpFdbEntry->dot1dTpFdbAddress[i] = vb->id[idx++];
    }
    if (vb->id_len > idx) return -1;
    return 0;
}

static bridge_mib_dot1dTpFdbEntry_t *
assign_dot1dTpFdbEntry(GSList *vbl)
{
    GSList *elem;
    bridge_mib_dot1dTpFdbEntry_t *dot1dTpFdbEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 17, 4, 3, 1};

    dot1dTpFdbEntry = bridge_mib_new_dot1dTpFdbEntry();
    if (! dot1dTpFdbEntry) {
        return NULL;
    }

    p = (char *) dot1dTpFdbEntry + sizeof(bridge_mib_dot1dTpFdbEntry_t);
    * (GSList **) p = vbl;

    if (unpack_dot1dTpFdbEntry((GSnmpVarBind *) vbl->data, dot1dTpFdbEntry) < 0) {
        g_warning("illegal dot1dTpFdbEntry instance identifier");
        g_free(dot1dTpFdbEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _dot1dTpFdbEntry, &idx) < 0) continue;

        switch (idx) {
        case 2:
            dot1dTpFdbEntry->dot1dTpFdbPort = &(vb->syntax.i32[0]);
            break;
        case 3:
            dot1dTpFdbEntry->dot1dTpFdbStatus = &(vb->syntax.i32[0]);
            break;
        };
    }

    return dot1dTpFdbEntry;
}

int
bridge_mib_get_dot1dTpFdbTable(GSnmpSession *s, bridge_mib_dot1dTpFdbEntry_t ***dot1dTpFdbEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 17, 4, 3, 1, 0};

    *dot1dTpFdbEntry = NULL;

    add_attributes(s, &in, base, 10, _dot1dTpFdbEntry);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *dot1dTpFdbEntry = (bridge_mib_dot1dTpFdbEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(bridge_mib_dot1dTpFdbEntry_t *));
    if (! *dot1dTpFdbEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*dot1dTpFdbEntry)[i] = assign_dot1dTpFdbEntry(row->data);
    }

    return 0;
}

void
bridge_mib_free_dot1dTpFdbEntry(bridge_mib_dot1dTpFdbEntry_t *dot1dTpFdbEntry)
{
    GSList *vbl;
    char *p;

    if (dot1dTpFdbEntry) {
        p = (char *) dot1dTpFdbEntry + sizeof(bridge_mib_dot1dTpFdbEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(dot1dTpFdbEntry);
    }
}

void
bridge_mib_free_dot1dTpFdbTable(bridge_mib_dot1dTpFdbEntry_t **dot1dTpFdbEntry)
{
    int i;

    if (dot1dTpFdbEntry) {
        for (i = 0; dot1dTpFdbEntry[i]; i++) {
            bridge_mib_free_dot1dTpFdbEntry(dot1dTpFdbEntry[i]);
        }
        g_free(dot1dTpFdbEntry);
    }
}

bridge_mib_dot1dTpPortEntry_t *
bridge_mib_new_dot1dTpPortEntry()
{
    bridge_mib_dot1dTpPortEntry_t *dot1dTpPortEntry;

    dot1dTpPortEntry = (bridge_mib_dot1dTpPortEntry_t *) g_malloc0(sizeof(bridge_mib_dot1dTpPortEntry_t) + sizeof(gpointer));
    return dot1dTpPortEntry;
}

static int
unpack_dot1dTpPortEntry(GSnmpVarBind *vb, bridge_mib_dot1dTpPortEntry_t *dot1dTpPortEntry)
{
    int idx = 11;

    if (vb->id_len < idx) return -1;
    dot1dTpPortEntry->dot1dTpPort = vb->id[idx++];
    if (vb->id_len > idx) return -1;
    return 0;
}

static bridge_mib_dot1dTpPortEntry_t *
assign_dot1dTpPortEntry(GSList *vbl)
{
    GSList *elem;
    bridge_mib_dot1dTpPortEntry_t *dot1dTpPortEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 17, 4, 4, 1};

    dot1dTpPortEntry = bridge_mib_new_dot1dTpPortEntry();
    if (! dot1dTpPortEntry) {
        return NULL;
    }

    p = (char *) dot1dTpPortEntry + sizeof(bridge_mib_dot1dTpPortEntry_t);
    * (GSList **) p = vbl;

    if (unpack_dot1dTpPortEntry((GSnmpVarBind *) vbl->data, dot1dTpPortEntry) < 0) {
        g_warning("illegal dot1dTpPortEntry instance identifier");
        g_free(dot1dTpPortEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _dot1dTpPortEntry, &idx) < 0) continue;

        switch (idx) {
        case 2:
            dot1dTpPortEntry->dot1dTpPortMaxInfo = &(vb->syntax.i32[0]);
            break;
        case 3:
            dot1dTpPortEntry->dot1dTpPortInFrames = &(vb->syntax.ui32[0]);
            break;
        case 4:
            dot1dTpPortEntry->dot1dTpPortOutFrames = &(vb->syntax.ui32[0]);
            break;
        case 5:
            dot1dTpPortEntry->dot1dTpPortInDiscards = &(vb->syntax.ui32[0]);
            break;
        };
    }

    return dot1dTpPortEntry;
}

int
bridge_mib_get_dot1dTpPortTable(GSnmpSession *s, bridge_mib_dot1dTpPortEntry_t ***dot1dTpPortEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 17, 4, 4, 1, 0};

    *dot1dTpPortEntry = NULL;

    add_attributes(s, &in, base, 10, _dot1dTpPortEntry);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *dot1dTpPortEntry = (bridge_mib_dot1dTpPortEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(bridge_mib_dot1dTpPortEntry_t *));
    if (! *dot1dTpPortEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*dot1dTpPortEntry)[i] = assign_dot1dTpPortEntry(row->data);
    }

    return 0;
}

void
bridge_mib_free_dot1dTpPortEntry(bridge_mib_dot1dTpPortEntry_t *dot1dTpPortEntry)
{
    GSList *vbl;
    char *p;

    if (dot1dTpPortEntry) {
        p = (char *) dot1dTpPortEntry + sizeof(bridge_mib_dot1dTpPortEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(dot1dTpPortEntry);
    }
}

void
bridge_mib_free_dot1dTpPortTable(bridge_mib_dot1dTpPortEntry_t **dot1dTpPortEntry)
{
    int i;

    if (dot1dTpPortEntry) {
        for (i = 0; dot1dTpPortEntry[i]; i++) {
            bridge_mib_free_dot1dTpPortEntry(dot1dTpPortEntry[i]);
        }
        g_free(dot1dTpPortEntry);
    }
}

bridge_mib_dot1dStaticEntry_t *
bridge_mib_new_dot1dStaticEntry()
{
    bridge_mib_dot1dStaticEntry_t *dot1dStaticEntry;

    dot1dStaticEntry = (bridge_mib_dot1dStaticEntry_t *) g_malloc0(sizeof(bridge_mib_dot1dStaticEntry_t) + sizeof(gpointer));
    return dot1dStaticEntry;
}

static int
unpack_dot1dStaticEntry(GSnmpVarBind *vb, bridge_mib_dot1dStaticEntry_t *dot1dStaticEntry)
{
    int i, len, idx = 11;

    len = 6;
    if (vb->id_len < idx + len) return -1;
    for (i = 0; i < len; i++) {
        dot1dStaticEntry->dot1dStaticAddress[i] = vb->id[idx++];
    }
    if (vb->id_len < idx) return -1;
    dot1dStaticEntry->dot1dStaticReceivePort = vb->id[idx++];
    if (vb->id_len > idx) return -1;
    return 0;
}

static bridge_mib_dot1dStaticEntry_t *
assign_dot1dStaticEntry(GSList *vbl)
{
    GSList *elem;
    bridge_mib_dot1dStaticEntry_t *dot1dStaticEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 2, 1, 17, 5, 1, 1};

    dot1dStaticEntry = bridge_mib_new_dot1dStaticEntry();
    if (! dot1dStaticEntry) {
        return NULL;
    }

    p = (char *) dot1dStaticEntry + sizeof(bridge_mib_dot1dStaticEntry_t);
    * (GSList **) p = vbl;

    if (unpack_dot1dStaticEntry((GSnmpVarBind *) vbl->data, dot1dStaticEntry) < 0) {
        g_warning("illegal dot1dStaticEntry instance identifier");
        g_free(dot1dStaticEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, base, sizeof(base)/sizeof(guint32),
                   _dot1dStaticEntry, &idx) < 0) continue;

        switch (idx) {
        case 3:
            dot1dStaticEntry->_dot1dStaticAllowedToGoToLength = vb->syntax_len;
            dot1dStaticEntry->dot1dStaticAllowedToGoTo = vb->syntax.uc;
            break;
        case 4:
            dot1dStaticEntry->dot1dStaticStatus = &(vb->syntax.i32[0]);
            break;
        };
    }

    return dot1dStaticEntry;
}

int
bridge_mib_get_dot1dStaticTable(GSnmpSession *s, bridge_mib_dot1dStaticEntry_t ***dot1dStaticEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 17, 5, 1, 1, 0};

    *dot1dStaticEntry = NULL;

    add_attributes(s, &in, base, 10, _dot1dStaticEntry);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *dot1dStaticEntry = (bridge_mib_dot1dStaticEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(bridge_mib_dot1dStaticEntry_t *));
    if (! *dot1dStaticEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*dot1dStaticEntry)[i] = assign_dot1dStaticEntry(row->data);
    }

    return 0;
}

void
bridge_mib_free_dot1dStaticEntry(bridge_mib_dot1dStaticEntry_t *dot1dStaticEntry)
{
    GSList *vbl;
    char *p;

    if (dot1dStaticEntry) {
        p = (char *) dot1dStaticEntry + sizeof(bridge_mib_dot1dStaticEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(dot1dStaticEntry);
    }
}

void
bridge_mib_free_dot1dStaticTable(bridge_mib_dot1dStaticEntry_t **dot1dStaticEntry)
{
    int i;

    if (dot1dStaticEntry) {
        for (i = 0; dot1dStaticEntry[i]; i++) {
            bridge_mib_free_dot1dStaticEntry(dot1dStaticEntry[i]);
        }
        g_free(dot1dStaticEntry);
    }
}


