/*							-- DO NOT EDIT --
 * This file has been generated by smidump
 * version 0.2.13 for the stools package.
 *
 * Derived from BRIDGE-MIB revision [unknown].
 *
 * $Id$
 */

#include "bridge-mib.h"

stls_table_t bridge_mib_enums_dot1dBaseType[] = {
    { 1, "unknown" },
    { 2, "transparent-only" },
    { 3, "sourceroute-only" },
    { 4, "srt" },
    { 0, NULL }
};

stls_table_t bridge_mib_enums_dot1dStpProtocolSpecification[] = {
    { 1, "unknown" },
    { 2, "decLb100" },
    { 3, "ieee8021d" },
    { 0, NULL }
};

stls_table_t bridge_mib_enums_dot1dStpPortState[] = {
    { 1, "disabled" },
    { 2, "blocking" },
    { 3, "listening" },
    { 4, "learning" },
    { 5, "forwarding" },
    { 6, "broken" },
    { 0, NULL }
};

stls_table_t bridge_mib_enums_dot1dStpPortEnable[] = {
    { 1, "enabled" },
    { 2, "disabled" },
    { 0, NULL }
};

stls_table_t bridge_mib_enums_dot1dTpFdbStatus[] = {
    { 1, "other" },
    { 2, "invalid" },
    { 3, "learned" },
    { 4, "self" },
    { 5, "mgmt" },
    { 0, NULL }
};

stls_table_t bridge_mib_enums_dot1dStaticStatus[] = {
    { 1, "other" },
    { 2, "invalid" },
    { 3, "permanent" },
    { 4, "deleteOnReset" },
    { 5, "deleteOnTimeout" },
    { 0, NULL }
};


static dot1dBase_t *
assign_dot1dBase(GSList *vbl)
{
    GSList *elem;
    dot1dBase_t *dot1dBase;
    char *p;

    dot1dBase = (dot1dBase_t *) g_malloc0(sizeof(dot1dBase_t) + sizeof(GSList *));
    if (! dot1dBase) {
        return NULL;
    }

    p = (char *) dot1dBase + sizeof(dot1dBase_t);
    * (GSList **) p = vbl;

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;
        if (vb->type == G_SNMP_ENDOFMIBVIEW
            || (vb->type == G_SNMP_NOSUCHOBJECT)
            || (vb->type == G_SNMP_NOSUCHINSTANCE)) {
            continue;
        }
        if (vb->id_len > 9 && vb->id[8] == 1) {
            dot1dBase->dot1dBaseBridgeAddress = vb->syntax.uc;
        }
        if (vb->id_len > 9 && vb->id[8] == 2) {
            dot1dBase->dot1dBaseNumPorts = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 9 && vb->id[8] == 3) {
            dot1dBase->dot1dBaseType = &(vb->syntax.i32[0]);
        }
    }

    return dot1dBase;
}

int
bridge_mib_get_dot1dBase(host_snmp *s, dot1dBase_t **dot1dBase)
{
    GSList *in = NULL, *out = NULL;
    static guint32 var[] = {1, 3, 6, 1, 2, 1, 17, 1, 0};

    *dot1dBase = NULL;

    var[8] = 1; stls_vbl_add_null(&in, var, 9);
    var[8] = 2; stls_vbl_add_null(&in, var, 9);
    var[8] = 3; stls_vbl_add_null(&in, var, 9);

    out = stls_snmp_getnext(s, in);
    stls_vbl_free(in);
    if (! out) {
        return -2;
    }

    *dot1dBase = assign_dot1dBase(out);

    return 0;
}

void
bridge_mib_free_dot1dBase(dot1dBase_t *dot1dBase)
{
    GSList *vbl;
    char *p;

    if (dot1dBase) {
        p = (char *) dot1dBase + sizeof(dot1dBase_t);
        vbl = * (GSList **) p;
        stls_vbl_free(vbl);
        g_free(dot1dBase);
    }
}

static dot1dBasePortEntry_t *
assign_dot1dBasePortEntry(GSList *vbl)
{
    GSList *elem;
    dot1dBasePortEntry_t *dot1dBasePortEntry;
    char *p;

    dot1dBasePortEntry = (dot1dBasePortEntry_t *) g_malloc0(sizeof(dot1dBasePortEntry_t) + sizeof(GSList *));
    if (! dot1dBasePortEntry) {
        return NULL;
    }

    p = (char *) dot1dBasePortEntry + sizeof(dot1dBasePortEntry_t);
    * (GSList **) p = vbl;

    {
        GSnmpVarBind *vb = (GSnmpVarBind *) vbl->data;
        if (vb->id_len < 12) return NULL;
        dot1dBasePortEntry->dot1dBasePort = (gint32 *) &(vb->id[11]);
        if (vb->id_len > 12) return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;
        if (vb->type == G_SNMP_ENDOFMIBVIEW
            || (vb->type == G_SNMP_NOSUCHOBJECT)
            || (vb->type == G_SNMP_NOSUCHINSTANCE)) {
            continue;
        }
        if (vb->id_len > 11 && vb->id[10] == 2) {
            dot1dBasePortEntry->dot1dBasePortIfIndex = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 11 && vb->id[10] == 3) {
            dot1dBasePortEntry->_dot1dBasePortCircuitLength = vb->syntax_len / sizeof(guint32);
            dot1dBasePortEntry->dot1dBasePortCircuit = vb->syntax.ui32;
        }
        if (vb->id_len > 11 && vb->id[10] == 4) {
            dot1dBasePortEntry->dot1dBasePortDelayExceededDiscards = &(vb->syntax.ui32[0]);
        }
        if (vb->id_len > 11 && vb->id[10] == 5) {
            dot1dBasePortEntry->dot1dBasePortMtuExceededDiscards = &(vb->syntax.ui32[0]);
        }
    }

    return dot1dBasePortEntry;
}

int
bridge_mib_get_dot1dBasePortEntry(host_snmp *s, dot1dBasePortEntry_t ***dot1dBasePortEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 var[] = {1, 3, 6, 1, 2, 1, 17, 1, 4, 1, 0};

    *dot1dBasePortEntry = NULL;

    var[10] = 2; stls_vbl_add_null(&in, var, 11);
    var[10] = 3; stls_vbl_add_null(&in, var, 11);
    var[10] = 4; stls_vbl_add_null(&in, var, 11);
    var[10] = 5; stls_vbl_add_null(&in, var, 11);

    out = stls_snmp_gettable(s, in);
    /* stls_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *dot1dBasePortEntry = (dot1dBasePortEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(dot1dBasePortEntry_t *));
    if (! *dot1dBasePortEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*dot1dBasePortEntry)[i] = assign_dot1dBasePortEntry(row->data);
    }

    return 0;
}

void
bridge_mib_free_dot1dBasePortEntry(dot1dBasePortEntry_t **dot1dBasePortEntry)
{
    GSList *vbl;
    char *p;
    int i;

    if (dot1dBasePortEntry) {
        for (i = 0; dot1dBasePortEntry[i]; i++) {
            p = (char *) dot1dBasePortEntry[i] + sizeof(dot1dBasePortEntry_t);
            vbl = * (GSList **) p;
            stls_vbl_free(vbl);
            g_free(dot1dBasePortEntry[i]);
        }
        g_free(dot1dBasePortEntry);
    }
}

static dot1dStp_t *
assign_dot1dStp(GSList *vbl)
{
    GSList *elem;
    dot1dStp_t *dot1dStp;
    char *p;

    dot1dStp = (dot1dStp_t *) g_malloc0(sizeof(dot1dStp_t) + sizeof(GSList *));
    if (! dot1dStp) {
        return NULL;
    }

    p = (char *) dot1dStp + sizeof(dot1dStp_t);
    * (GSList **) p = vbl;

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;
        if (vb->type == G_SNMP_ENDOFMIBVIEW
            || (vb->type == G_SNMP_NOSUCHOBJECT)
            || (vb->type == G_SNMP_NOSUCHINSTANCE)) {
            continue;
        }
        if (vb->id_len > 9 && vb->id[8] == 1) {
            dot1dStp->dot1dStpProtocolSpecification = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 9 && vb->id[8] == 2) {
            dot1dStp->dot1dStpPriority = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 9 && vb->id[8] == 3) {
            dot1dStp->dot1dStpTimeSinceTopologyChange = &(vb->syntax.ui32[0]);
        }
        if (vb->id_len > 9 && vb->id[8] == 4) {
            dot1dStp->dot1dStpTopChanges = &(vb->syntax.ui32[0]);
        }
        if (vb->id_len > 9 && vb->id[8] == 5) {
            dot1dStp->dot1dStpDesignatedRoot = vb->syntax.uc;
        }
        if (vb->id_len > 9 && vb->id[8] == 6) {
            dot1dStp->dot1dStpRootCost = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 9 && vb->id[8] == 7) {
            dot1dStp->dot1dStpRootPort = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 9 && vb->id[8] == 8) {
            dot1dStp->dot1dStpMaxAge = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 9 && vb->id[8] == 9) {
            dot1dStp->dot1dStpHelloTime = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 9 && vb->id[8] == 10) {
            dot1dStp->dot1dStpHoldTime = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 9 && vb->id[8] == 11) {
            dot1dStp->dot1dStpForwardDelay = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 9 && vb->id[8] == 12) {
            dot1dStp->dot1dStpBridgeMaxAge = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 9 && vb->id[8] == 13) {
            dot1dStp->dot1dStpBridgeHelloTime = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 9 && vb->id[8] == 14) {
            dot1dStp->dot1dStpBridgeForwardDelay = &(vb->syntax.i32[0]);
        }
    }

    return dot1dStp;
}

int
bridge_mib_get_dot1dStp(host_snmp *s, dot1dStp_t **dot1dStp)
{
    GSList *in = NULL, *out = NULL;
    static guint32 var[] = {1, 3, 6, 1, 2, 1, 17, 2, 0};

    *dot1dStp = NULL;

    var[8] = 1; stls_vbl_add_null(&in, var, 9);
    var[8] = 2; stls_vbl_add_null(&in, var, 9);
    var[8] = 3; stls_vbl_add_null(&in, var, 9);
    var[8] = 4; stls_vbl_add_null(&in, var, 9);
    var[8] = 5; stls_vbl_add_null(&in, var, 9);
    var[8] = 6; stls_vbl_add_null(&in, var, 9);
    var[8] = 7; stls_vbl_add_null(&in, var, 9);
    var[8] = 8; stls_vbl_add_null(&in, var, 9);
    var[8] = 9; stls_vbl_add_null(&in, var, 9);
    var[8] = 10; stls_vbl_add_null(&in, var, 9);
    var[8] = 11; stls_vbl_add_null(&in, var, 9);
    var[8] = 12; stls_vbl_add_null(&in, var, 9);
    var[8] = 13; stls_vbl_add_null(&in, var, 9);
    var[8] = 14; stls_vbl_add_null(&in, var, 9);

    out = stls_snmp_getnext(s, in);
    stls_vbl_free(in);
    if (! out) {
        return -2;
    }

    *dot1dStp = assign_dot1dStp(out);

    return 0;
}

void
bridge_mib_free_dot1dStp(dot1dStp_t *dot1dStp)
{
    GSList *vbl;
    char *p;

    if (dot1dStp) {
        p = (char *) dot1dStp + sizeof(dot1dStp_t);
        vbl = * (GSList **) p;
        stls_vbl_free(vbl);
        g_free(dot1dStp);
    }
}

static dot1dStpPortEntry_t *
assign_dot1dStpPortEntry(GSList *vbl)
{
    GSList *elem;
    dot1dStpPortEntry_t *dot1dStpPortEntry;
    char *p;

    dot1dStpPortEntry = (dot1dStpPortEntry_t *) g_malloc0(sizeof(dot1dStpPortEntry_t) + sizeof(GSList *));
    if (! dot1dStpPortEntry) {
        return NULL;
    }

    p = (char *) dot1dStpPortEntry + sizeof(dot1dStpPortEntry_t);
    * (GSList **) p = vbl;

    {
        GSnmpVarBind *vb = (GSnmpVarBind *) vbl->data;
        if (vb->id_len < 12) return NULL;
        dot1dStpPortEntry->dot1dStpPort = (gint32 *) &(vb->id[11]);
        if (vb->id_len > 12) return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;
        if (vb->type == G_SNMP_ENDOFMIBVIEW
            || (vb->type == G_SNMP_NOSUCHOBJECT)
            || (vb->type == G_SNMP_NOSUCHINSTANCE)) {
            continue;
        }
        if (vb->id_len > 11 && vb->id[10] == 2) {
            dot1dStpPortEntry->dot1dStpPortPriority = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 11 && vb->id[10] == 3) {
            dot1dStpPortEntry->dot1dStpPortState = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 11 && vb->id[10] == 4) {
            dot1dStpPortEntry->dot1dStpPortEnable = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 11 && vb->id[10] == 5) {
            dot1dStpPortEntry->dot1dStpPortPathCost = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 11 && vb->id[10] == 6) {
            dot1dStpPortEntry->dot1dStpPortDesignatedRoot = vb->syntax.uc;
        }
        if (vb->id_len > 11 && vb->id[10] == 7) {
            dot1dStpPortEntry->dot1dStpPortDesignatedCost = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 11 && vb->id[10] == 8) {
            dot1dStpPortEntry->dot1dStpPortDesignatedBridge = vb->syntax.uc;
        }
        if (vb->id_len > 11 && vb->id[10] == 9) {
            dot1dStpPortEntry->dot1dStpPortDesignatedPort = vb->syntax.uc;
        }
        if (vb->id_len > 11 && vb->id[10] == 10) {
            dot1dStpPortEntry->dot1dStpPortForwardTransitions = &(vb->syntax.ui32[0]);
        }
    }

    return dot1dStpPortEntry;
}

int
bridge_mib_get_dot1dStpPortEntry(host_snmp *s, dot1dStpPortEntry_t ***dot1dStpPortEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 var[] = {1, 3, 6, 1, 2, 1, 17, 2, 15, 1, 0};

    *dot1dStpPortEntry = NULL;

    var[10] = 2; stls_vbl_add_null(&in, var, 11);
    var[10] = 3; stls_vbl_add_null(&in, var, 11);
    var[10] = 4; stls_vbl_add_null(&in, var, 11);
    var[10] = 5; stls_vbl_add_null(&in, var, 11);
    var[10] = 6; stls_vbl_add_null(&in, var, 11);
    var[10] = 7; stls_vbl_add_null(&in, var, 11);
    var[10] = 8; stls_vbl_add_null(&in, var, 11);
    var[10] = 9; stls_vbl_add_null(&in, var, 11);
    var[10] = 10; stls_vbl_add_null(&in, var, 11);

    out = stls_snmp_gettable(s, in);
    /* stls_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *dot1dStpPortEntry = (dot1dStpPortEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(dot1dStpPortEntry_t *));
    if (! *dot1dStpPortEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*dot1dStpPortEntry)[i] = assign_dot1dStpPortEntry(row->data);
    }

    return 0;
}

void
bridge_mib_free_dot1dStpPortEntry(dot1dStpPortEntry_t **dot1dStpPortEntry)
{
    GSList *vbl;
    char *p;
    int i;

    if (dot1dStpPortEntry) {
        for (i = 0; dot1dStpPortEntry[i]; i++) {
            p = (char *) dot1dStpPortEntry[i] + sizeof(dot1dStpPortEntry_t);
            vbl = * (GSList **) p;
            stls_vbl_free(vbl);
            g_free(dot1dStpPortEntry[i]);
        }
        g_free(dot1dStpPortEntry);
    }
}

static dot1dTp_t *
assign_dot1dTp(GSList *vbl)
{
    GSList *elem;
    dot1dTp_t *dot1dTp;
    char *p;

    dot1dTp = (dot1dTp_t *) g_malloc0(sizeof(dot1dTp_t) + sizeof(GSList *));
    if (! dot1dTp) {
        return NULL;
    }

    p = (char *) dot1dTp + sizeof(dot1dTp_t);
    * (GSList **) p = vbl;

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;
        if (vb->type == G_SNMP_ENDOFMIBVIEW
            || (vb->type == G_SNMP_NOSUCHOBJECT)
            || (vb->type == G_SNMP_NOSUCHINSTANCE)) {
            continue;
        }
        if (vb->id_len > 9 && vb->id[8] == 1) {
            dot1dTp->dot1dTpLearnedEntryDiscards = &(vb->syntax.ui32[0]);
        }
        if (vb->id_len > 9 && vb->id[8] == 2) {
            dot1dTp->dot1dTpAgingTime = &(vb->syntax.i32[0]);
        }
    }

    return dot1dTp;
}

int
bridge_mib_get_dot1dTp(host_snmp *s, dot1dTp_t **dot1dTp)
{
    GSList *in = NULL, *out = NULL;
    static guint32 var[] = {1, 3, 6, 1, 2, 1, 17, 4, 0};

    *dot1dTp = NULL;

    var[8] = 1; stls_vbl_add_null(&in, var, 9);
    var[8] = 2; stls_vbl_add_null(&in, var, 9);

    out = stls_snmp_getnext(s, in);
    stls_vbl_free(in);
    if (! out) {
        return -2;
    }

    *dot1dTp = assign_dot1dTp(out);

    return 0;
}

void
bridge_mib_free_dot1dTp(dot1dTp_t *dot1dTp)
{
    GSList *vbl;
    char *p;

    if (dot1dTp) {
        p = (char *) dot1dTp + sizeof(dot1dTp_t);
        vbl = * (GSList **) p;
        stls_vbl_free(vbl);
        g_free(dot1dTp);
    }
}

static dot1dTpFdbEntry_t *
assign_dot1dTpFdbEntry(GSList *vbl)
{
    GSList *elem;
    dot1dTpFdbEntry_t *dot1dTpFdbEntry;
    char *p;

    dot1dTpFdbEntry = (dot1dTpFdbEntry_t *) g_malloc0(sizeof(dot1dTpFdbEntry_t) + sizeof(GSList *));
    if (! dot1dTpFdbEntry) {
        return NULL;
    }

    p = (char *) dot1dTpFdbEntry + sizeof(dot1dTpFdbEntry_t);
    * (GSList **) p = vbl;

    {
        GSnmpVarBind *vb = (GSnmpVarBind *) vbl->data;
        if (vb->id_len < 12) return NULL;
        /* XXX fix this dot1dTpFdbEntry->dot1dTpFdbAddress = ?; */
        if (vb->id_len > 11) return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;
        if (vb->type == G_SNMP_ENDOFMIBVIEW
            || (vb->type == G_SNMP_NOSUCHOBJECT)
            || (vb->type == G_SNMP_NOSUCHINSTANCE)) {
            continue;
        }
        if (vb->id_len > 11 && vb->id[10] == 2) {
            dot1dTpFdbEntry->dot1dTpFdbPort = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 11 && vb->id[10] == 3) {
            dot1dTpFdbEntry->dot1dTpFdbStatus = &(vb->syntax.i32[0]);
        }
    }

    return dot1dTpFdbEntry;
}

int
bridge_mib_get_dot1dTpFdbEntry(host_snmp *s, dot1dTpFdbEntry_t ***dot1dTpFdbEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 var[] = {1, 3, 6, 1, 2, 1, 17, 4, 3, 1, 0};

    *dot1dTpFdbEntry = NULL;

    var[10] = 2; stls_vbl_add_null(&in, var, 11);
    var[10] = 3; stls_vbl_add_null(&in, var, 11);

    out = stls_snmp_gettable(s, in);
    /* stls_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *dot1dTpFdbEntry = (dot1dTpFdbEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(dot1dTpFdbEntry_t *));
    if (! *dot1dTpFdbEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*dot1dTpFdbEntry)[i] = assign_dot1dTpFdbEntry(row->data);
    }

    return 0;
}

void
bridge_mib_free_dot1dTpFdbEntry(dot1dTpFdbEntry_t **dot1dTpFdbEntry)
{
    GSList *vbl;
    char *p;
    int i;

    if (dot1dTpFdbEntry) {
        for (i = 0; dot1dTpFdbEntry[i]; i++) {
            p = (char *) dot1dTpFdbEntry[i] + sizeof(dot1dTpFdbEntry_t);
            vbl = * (GSList **) p;
            stls_vbl_free(vbl);
            g_free(dot1dTpFdbEntry[i]);
        }
        g_free(dot1dTpFdbEntry);
    }
}

static dot1dTpPortEntry_t *
assign_dot1dTpPortEntry(GSList *vbl)
{
    GSList *elem;
    dot1dTpPortEntry_t *dot1dTpPortEntry;
    char *p;

    dot1dTpPortEntry = (dot1dTpPortEntry_t *) g_malloc0(sizeof(dot1dTpPortEntry_t) + sizeof(GSList *));
    if (! dot1dTpPortEntry) {
        return NULL;
    }

    p = (char *) dot1dTpPortEntry + sizeof(dot1dTpPortEntry_t);
    * (GSList **) p = vbl;

    {
        GSnmpVarBind *vb = (GSnmpVarBind *) vbl->data;
        if (vb->id_len < 12) return NULL;
        dot1dTpPortEntry->dot1dTpPort = (gint32 *) &(vb->id[11]);
        if (vb->id_len > 12) return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;
        if (vb->type == G_SNMP_ENDOFMIBVIEW
            || (vb->type == G_SNMP_NOSUCHOBJECT)
            || (vb->type == G_SNMP_NOSUCHINSTANCE)) {
            continue;
        }
        if (vb->id_len > 11 && vb->id[10] == 2) {
            dot1dTpPortEntry->dot1dTpPortMaxInfo = &(vb->syntax.i32[0]);
        }
        if (vb->id_len > 11 && vb->id[10] == 3) {
            dot1dTpPortEntry->dot1dTpPortInFrames = &(vb->syntax.ui32[0]);
        }
        if (vb->id_len > 11 && vb->id[10] == 4) {
            dot1dTpPortEntry->dot1dTpPortOutFrames = &(vb->syntax.ui32[0]);
        }
        if (vb->id_len > 11 && vb->id[10] == 5) {
            dot1dTpPortEntry->dot1dTpPortInDiscards = &(vb->syntax.ui32[0]);
        }
    }

    return dot1dTpPortEntry;
}

int
bridge_mib_get_dot1dTpPortEntry(host_snmp *s, dot1dTpPortEntry_t ***dot1dTpPortEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 var[] = {1, 3, 6, 1, 2, 1, 17, 4, 4, 1, 0};

    *dot1dTpPortEntry = NULL;

    var[10] = 2; stls_vbl_add_null(&in, var, 11);
    var[10] = 3; stls_vbl_add_null(&in, var, 11);
    var[10] = 4; stls_vbl_add_null(&in, var, 11);
    var[10] = 5; stls_vbl_add_null(&in, var, 11);

    out = stls_snmp_gettable(s, in);
    /* stls_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *dot1dTpPortEntry = (dot1dTpPortEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(dot1dTpPortEntry_t *));
    if (! *dot1dTpPortEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*dot1dTpPortEntry)[i] = assign_dot1dTpPortEntry(row->data);
    }

    return 0;
}

void
bridge_mib_free_dot1dTpPortEntry(dot1dTpPortEntry_t **dot1dTpPortEntry)
{
    GSList *vbl;
    char *p;
    int i;

    if (dot1dTpPortEntry) {
        for (i = 0; dot1dTpPortEntry[i]; i++) {
            p = (char *) dot1dTpPortEntry[i] + sizeof(dot1dTpPortEntry_t);
            vbl = * (GSList **) p;
            stls_vbl_free(vbl);
            g_free(dot1dTpPortEntry[i]);
        }
        g_free(dot1dTpPortEntry);
    }
}

static dot1dStaticEntry_t *
assign_dot1dStaticEntry(GSList *vbl)
{
    GSList *elem;
    dot1dStaticEntry_t *dot1dStaticEntry;
    char *p;

    dot1dStaticEntry = (dot1dStaticEntry_t *) g_malloc0(sizeof(dot1dStaticEntry_t) + sizeof(GSList *));
    if (! dot1dStaticEntry) {
        return NULL;
    }

    p = (char *) dot1dStaticEntry + sizeof(dot1dStaticEntry_t);
    * (GSList **) p = vbl;

    {
        GSnmpVarBind *vb = (GSnmpVarBind *) vbl->data;
        if (vb->id_len < 12) return NULL;
        /* XXX fix this dot1dStaticEntry->dot1dStaticAddress = ?; */
        dot1dStaticEntry->dot1dStaticReceivePort = (gint32 *) &(vb->id[11]);
        if (vb->id_len > 12) return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;
        if (vb->type == G_SNMP_ENDOFMIBVIEW
            || (vb->type == G_SNMP_NOSUCHOBJECT)
            || (vb->type == G_SNMP_NOSUCHINSTANCE)) {
            continue;
        }
        if (vb->id_len > 11 && vb->id[10] == 3) {
            dot1dStaticEntry->_dot1dStaticAllowedToGoToLength = vb->syntax_len;
            dot1dStaticEntry->dot1dStaticAllowedToGoTo = vb->syntax.uc;
        }
        if (vb->id_len > 11 && vb->id[10] == 4) {
            dot1dStaticEntry->dot1dStaticStatus = &(vb->syntax.i32[0]);
        }
    }

    return dot1dStaticEntry;
}

int
bridge_mib_get_dot1dStaticEntry(host_snmp *s, dot1dStaticEntry_t ***dot1dStaticEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 var[] = {1, 3, 6, 1, 2, 1, 17, 5, 1, 1, 0};

    *dot1dStaticEntry = NULL;

    var[10] = 3; stls_vbl_add_null(&in, var, 11);
    var[10] = 4; stls_vbl_add_null(&in, var, 11);

    out = stls_snmp_gettable(s, in);
    /* stls_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *dot1dStaticEntry = (dot1dStaticEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(dot1dStaticEntry_t *));
    if (! *dot1dStaticEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*dot1dStaticEntry)[i] = assign_dot1dStaticEntry(row->data);
    }

    return 0;
}

void
bridge_mib_free_dot1dStaticEntry(dot1dStaticEntry_t **dot1dStaticEntry)
{
    GSList *vbl;
    char *p;
    int i;

    if (dot1dStaticEntry) {
        for (i = 0; dot1dStaticEntry[i]; i++) {
            p = (char *) dot1dStaticEntry[i] + sizeof(dot1dStaticEntry_t);
            vbl = * (GSList **) p;
            stls_vbl_free(vbl);
            g_free(dot1dStaticEntry[i]);
        }
        g_free(dot1dStaticEntry);
    }
}


