/*							-- DO NOT EDIT --
 * This file has been generated by smidump
 * version 0.3.0 for the scli package.
 *
 * Derived from IP-FORWARD-MIB:
 *   The MIB module for the display of CIDR multipath IP Routes.
 *
 * Revision 1996-09-19 00:00:
 *   Revisions made by the OSPF WG.
 *
 * $Id$
 */

#include "ip-forward-mib.h"

GSnmpEnum const ip_forward_mib_enums_ipForwardType[] = {
    { IP_FORWARD_MIB_IPFORWARDTYPE_OTHER,	"other" },
    { IP_FORWARD_MIB_IPFORWARDTYPE_INVALID,	"invalid" },
    { IP_FORWARD_MIB_IPFORWARDTYPE_LOCAL,	"local" },
    { IP_FORWARD_MIB_IPFORWARDTYPE_REMOTE,	"remote" },
    { 0, NULL }
};

GSnmpEnum const ip_forward_mib_enums_ipForwardProto[] = {
    { IP_FORWARD_MIB_IPFORWARDPROTO_OTHER,	"other" },
    { IP_FORWARD_MIB_IPFORWARDPROTO_LOCAL,	"local" },
    { IP_FORWARD_MIB_IPFORWARDPROTO_NETMGMT,	"netmgmt" },
    { IP_FORWARD_MIB_IPFORWARDPROTO_ICMP,	"icmp" },
    { IP_FORWARD_MIB_IPFORWARDPROTO_EGP,	"egp" },
    { IP_FORWARD_MIB_IPFORWARDPROTO_GGP,	"ggp" },
    { IP_FORWARD_MIB_IPFORWARDPROTO_HELLO,	"hello" },
    { IP_FORWARD_MIB_IPFORWARDPROTO_RIP,	"rip" },
    { IP_FORWARD_MIB_IPFORWARDPROTO_IS_IS,	"is-is" },
    { IP_FORWARD_MIB_IPFORWARDPROTO_ES_IS,	"es-is" },
    { IP_FORWARD_MIB_IPFORWARDPROTO_CISCOIGRP,	"ciscoIgrp" },
    { IP_FORWARD_MIB_IPFORWARDPROTO_BBNSPFIGP,	"bbnSpfIgp" },
    { IP_FORWARD_MIB_IPFORWARDPROTO_OSPF,	"ospf" },
    { IP_FORWARD_MIB_IPFORWARDPROTO_BGP,	"bgp" },
    { IP_FORWARD_MIB_IPFORWARDPROTO_IDPR,	"idpr" },
    { 0, NULL }
};

GSnmpEnum const ip_forward_mib_enums_ipCidrRouteType[] = {
    { IP_FORWARD_MIB_IPCIDRROUTETYPE_OTHER,	"other" },
    { IP_FORWARD_MIB_IPCIDRROUTETYPE_REJECT,	"reject" },
    { IP_FORWARD_MIB_IPCIDRROUTETYPE_LOCAL,	"local" },
    { IP_FORWARD_MIB_IPCIDRROUTETYPE_REMOTE,	"remote" },
    { 0, NULL }
};

GSnmpEnum const ip_forward_mib_enums_ipCidrRouteProto[] = {
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_OTHER,	"other" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_LOCAL,	"local" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_NETMGMT,	"netmgmt" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_ICMP,	"icmp" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_EGP,	"egp" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_GGP,	"ggp" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_HELLO,	"hello" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_RIP,	"rip" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_ISIS,	"isIs" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_ESIS,	"esIs" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_CISCOIGRP,	"ciscoIgrp" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_BBNSPFIGP,	"bbnSpfIgp" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_OSPF,	"ospf" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_BGP,	"bgp" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_IDPR,	"idpr" },
    { IP_FORWARD_MIB_IPCIDRROUTEPROTO_CISCOEIGRP,	"ciscoEigrp" },
    { 0, NULL }
};

GSnmpEnum const ip_forward_mib_enums_ipCidrRouteStatus[] = {
    { IP_FORWARD_MIB_IPCIDRROUTESTATUS_ACTIVE,	"active" },
    { IP_FORWARD_MIB_IPCIDRROUTESTATUS_NOTINSERVICE,	"notInService" },
    { IP_FORWARD_MIB_IPCIDRROUTESTATUS_NOTREADY,	"notReady" },
    { IP_FORWARD_MIB_IPCIDRROUTESTATUS_CREATEANDGO,	"createAndGo" },
    { IP_FORWARD_MIB_IPCIDRROUTESTATUS_CREATEANDWAIT,	"createAndWait" },
    { IP_FORWARD_MIB_IPCIDRROUTESTATUS_DESTROY,	"destroy" },
    { 0, NULL }
};


typedef struct {
    guint32 const     subid;
    GSnmpVarBindType  type;
    gint              tag;
    gchar            *label;
} attribute_t;

static void
add_attributes(GSnmpSession *s, GSList **vbl, guint32 *base, guint8 len,
                guint idx, attribute_t *attributes, gint mask)
{
    int i;

    for (i = 0; attributes[i].label; i++) {
        if (! mask || (mask & attributes[i].tag)) {
            if (attributes[i].type != G_SNMP_COUNTER64
                || s->version > G_SNMP_V1) {
                base[idx] = attributes[i].subid;
                g_snmp_vbl_add_null(vbl, base, len);
            }
        }
    }
}

static int
lookup(GSnmpVarBind *vb, guint32 const *base, guint16 const base_len,
	    attribute_t *attributes, guint32 *idx)
{
    int i;

    if (vb->type == G_SNMP_ENDOFMIBVIEW
        || (vb->type == G_SNMP_NOSUCHOBJECT)
        || (vb->type == G_SNMP_NOSUCHINSTANCE)) {
        return -1;
    }
    
    if (memcmp(vb->id, base, base_len * sizeof(guint32)) != 0) {
	return -2;
    }

    for (i = 0; attributes[i].label; i++) {
	if (vb->id_len > base_len && vb->id[base_len] == attributes[i].subid) {
	    if (vb->type != attributes[i].type) {
		const char *a = gsnmp_enum_get_label(gsnmp_enum_type_table, vb->type);
		const char *b = gsnmp_enum_get_label(gsnmp_enum_type_table, attributes[i].type);
		g_warning("%s: type mismatch: %s%s%s", attributes[i].label,
		          (a) ? a : "", (a || b) ? " != " : "", (b) ? b : "");
		return -3;
	    }
	    *idx = attributes[i].subid;
	    return 0;
	}
    }
    
    return -4;
}

static guint32 const oid_ipForward[] = {1, 3, 6, 1, 2, 1, 4, 24};

static attribute_t attr_ipForward[] = {
    { 1, G_SNMP_UNSIGNED32, IP_FORWARD_MIB_IPFORWARDNUMBER, "ipForwardNumber" },
    { 3, G_SNMP_UNSIGNED32, IP_FORWARD_MIB_IPCIDRROUTENUMBER, "ipCidrRouteNumber" },
    { 0, 0, 0, NULL }
};

static guint32 const oid_ipForwardEntry[] = {1, 3, 6, 1, 2, 1, 4, 24, 2, 1};

static attribute_t attr_ipForwardEntry[] = {
    { 2, G_SNMP_IPADDRESS, IP_FORWARD_MIB_IPFORWARDMASK, "ipForwardMask" },
    { 5, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPFORWARDIFINDEX, "ipForwardIfIndex" },
    { 6, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPFORWARDTYPE, "ipForwardType" },
    { 8, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPFORWARDAGE, "ipForwardAge" },
    { 9, G_SNMP_OBJECTID, IP_FORWARD_MIB_IPFORWARDINFO, "ipForwardInfo" },
    { 10, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPFORWARDNEXTHOPAS, "ipForwardNextHopAS" },
    { 11, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPFORWARDMETRIC1, "ipForwardMetric1" },
    { 12, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPFORWARDMETRIC2, "ipForwardMetric2" },
    { 13, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPFORWARDMETRIC3, "ipForwardMetric3" },
    { 14, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPFORWARDMETRIC4, "ipForwardMetric4" },
    { 15, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPFORWARDMETRIC5, "ipForwardMetric5" },
    { 0, 0, 0, NULL }
};

static guint32 const oid_ipCidrRouteEntry[] = {1, 3, 6, 1, 2, 1, 4, 24, 4, 1};

static attribute_t attr_ipCidrRouteEntry[] = {
    { 5, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPCIDRROUTEIFINDEX, "ipCidrRouteIfIndex" },
    { 6, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPCIDRROUTETYPE, "ipCidrRouteType" },
    { 7, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPCIDRROUTEPROTO, "ipCidrRouteProto" },
    { 8, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPCIDRROUTEAGE, "ipCidrRouteAge" },
    { 9, G_SNMP_OBJECTID, IP_FORWARD_MIB_IPCIDRROUTEINFO, "ipCidrRouteInfo" },
    { 10, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPCIDRROUTENEXTHOPAS, "ipCidrRouteNextHopAS" },
    { 11, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPCIDRROUTEMETRIC1, "ipCidrRouteMetric1" },
    { 12, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPCIDRROUTEMETRIC2, "ipCidrRouteMetric2" },
    { 13, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPCIDRROUTEMETRIC3, "ipCidrRouteMetric3" },
    { 14, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPCIDRROUTEMETRIC4, "ipCidrRouteMetric4" },
    { 15, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPCIDRROUTEMETRIC5, "ipCidrRouteMetric5" },
    { 16, G_SNMP_INTEGER32, IP_FORWARD_MIB_IPCIDRROUTESTATUS, "ipCidrRouteStatus" },
    { 0, 0, 0, NULL }
};


ip_forward_mib_ipForward_t *
ip_forward_mib_new_ipForward()
{
    ip_forward_mib_ipForward_t *ipForward;

    ipForward = (ip_forward_mib_ipForward_t *) g_malloc0(sizeof(ip_forward_mib_ipForward_t) + sizeof(gpointer));
    return ipForward;
}

static ip_forward_mib_ipForward_t *
assign_ipForward(GSList *vbl)
{
    GSList *elem;
    ip_forward_mib_ipForward_t *ipForward;
    guint32 idx;
    char *p;

    ipForward = ip_forward_mib_new_ipForward();
    if (! ipForward) {
        return NULL;
    }

    p = (char *) ipForward + sizeof(ip_forward_mib_ipForward_t);
    * (GSList **) p = vbl;

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, oid_ipForward, sizeof(oid_ipForward)/sizeof(guint32),
                   attr_ipForward, &idx) < 0) continue;

        switch (idx) {
        case 1:
            ipForward->ipForwardNumber = &(vb->syntax.ui32[0]);
            break;
        case 3:
            ipForward->ipCidrRouteNumber = &(vb->syntax.ui32[0]);
            break;
        };
    }

    return ipForward;
}

void
ip_forward_mib_get_ipForward(GSnmpSession *s, ip_forward_mib_ipForward_t **ipForward, gint mask)
{
    GSList *in = NULL, *out = NULL;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 4, 24, 0};

    *ipForward = NULL;

    add_attributes(s, &in, base, 9, 8, attr_ipForward, mask);

    out = g_snmp_session_sync_getnext(s, in);
    g_snmp_vbl_free(in);
    if (out) {
        if (s->error_status != G_SNMP_ERR_NOERROR) {
            g_snmp_vbl_free(out);
            return;
        }
        *ipForward = assign_ipForward(out);
    }
}

void
ip_forward_mib_free_ipForward(ip_forward_mib_ipForward_t *ipForward)
{
    GSList *vbl;
    char *p;

    if (ipForward) {
        p = (char *) ipForward + sizeof(ip_forward_mib_ipForward_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(ipForward);
    }
}

ip_forward_mib_ipForwardEntry_t *
ip_forward_mib_new_ipForwardEntry()
{
    ip_forward_mib_ipForwardEntry_t *ipForwardEntry;

    ipForwardEntry = (ip_forward_mib_ipForwardEntry_t *) g_malloc0(sizeof(ip_forward_mib_ipForwardEntry_t) + sizeof(gpointer));
    return ipForwardEntry;
}

static int
unpack_ipForwardEntry(GSnmpVarBind *vb, ip_forward_mib_ipForwardEntry_t *ipForwardEntry)
{
    int idx = 11;
    guint16 i, len;

    len = 4;
    if (vb->id_len < idx + len) return -1;
    if (len != 4) return -1;
    if (vb->id_len < idx + len) return -1;
    for (i = 0; i < len; i++) {
        ipForwardEntry->ipForwardDest[i] = vb->id[idx++];
    }
    if (vb->id_len < idx) return -1;
    ipForwardEntry->ipForwardProto = vb->id[idx++];
    if (vb->id_len < idx) return -1;
    ipForwardEntry->ipForwardPolicy = vb->id[idx++];
    len = 4;
    if (vb->id_len < idx + len) return -1;
    if (len != 4) return -1;
    if (vb->id_len < idx + len) return -1;
    for (i = 0; i < len; i++) {
        ipForwardEntry->ipForwardNextHop[i] = vb->id[idx++];
    }
    if (vb->id_len > idx) return -1;
    return 0;
}

static int
pack_ipForwardEntry(guint32 *base, guchar *ipForwardDest, gint32 ipForwardProto, gint32 ipForwardPolicy, guchar *ipForwardNextHop)
{
    int idx = 11;
    guint16 i, len;

    len = 4;
    if (len != 4) return -1;
    for (i = 0; i < len; i++) {
        base[idx++] = ipForwardDest[i];
        if (idx >= 128) return -1;
    }
    base[idx++] = ipForwardProto;
    base[idx++] = ipForwardPolicy;
    len = 4;
    if (len != 4) return -1;
    for (i = 0; i < len; i++) {
        base[idx++] = ipForwardNextHop[i];
        if (idx >= 128) return -1;
    }
    return idx;
}

static ip_forward_mib_ipForwardEntry_t *
assign_ipForwardEntry(GSList *vbl)
{
    GSList *elem;
    ip_forward_mib_ipForwardEntry_t *ipForwardEntry;
    guint32 idx;
    char *p;

    ipForwardEntry = ip_forward_mib_new_ipForwardEntry();
    if (! ipForwardEntry) {
        return NULL;
    }

    p = (char *) ipForwardEntry + sizeof(ip_forward_mib_ipForwardEntry_t);
    * (GSList **) p = vbl;

    if (unpack_ipForwardEntry((GSnmpVarBind *) vbl->data, ipForwardEntry) < 0) {
        g_warning("illegal ipForwardEntry instance identifier");
        g_free(ipForwardEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, oid_ipForwardEntry, sizeof(oid_ipForwardEntry)/sizeof(guint32),
                   attr_ipForwardEntry, &idx) < 0) continue;

        switch (idx) {
        case 2:
            if (vb->syntax_len != 4) break;
            ipForwardEntry->ipForwardMask = vb->syntax.uc;
            break;
        case 5:
            ipForwardEntry->ipForwardIfIndex = &(vb->syntax.i32[0]);
            break;
        case 6:
            ipForwardEntry->ipForwardType = &(vb->syntax.i32[0]);
            break;
        case 8:
            ipForwardEntry->ipForwardAge = &(vb->syntax.i32[0]);
            break;
        case 9:
            if (vb->syntax_len > 128) break;
            ipForwardEntry->_ipForwardInfoLength = vb->syntax_len / sizeof(guint32);
            ipForwardEntry->ipForwardInfo = vb->syntax.ui32;
            break;
        case 10:
            ipForwardEntry->ipForwardNextHopAS = &(vb->syntax.i32[0]);
            break;
        case 11:
            ipForwardEntry->ipForwardMetric1 = &(vb->syntax.i32[0]);
            break;
        case 12:
            ipForwardEntry->ipForwardMetric2 = &(vb->syntax.i32[0]);
            break;
        case 13:
            ipForwardEntry->ipForwardMetric3 = &(vb->syntax.i32[0]);
            break;
        case 14:
            ipForwardEntry->ipForwardMetric4 = &(vb->syntax.i32[0]);
            break;
        case 15:
            ipForwardEntry->ipForwardMetric5 = &(vb->syntax.i32[0]);
            break;
        };
    }

    return ipForwardEntry;
}

void
ip_forward_mib_get_ipForwardTable(GSnmpSession *s, ip_forward_mib_ipForwardEntry_t ***ipForwardEntry, gint mask)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 4, 24, 2, 1, 0};

    *ipForwardEntry = NULL;

    add_attributes(s, &in, base, 11, 10, attr_ipForwardEntry, mask);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */

    if (out) {
        *ipForwardEntry = (ip_forward_mib_ipForwardEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(ip_forward_mib_ipForwardEntry_t *));
        if (! *ipForwardEntry) {
            s->error_status = G_SNMP_ERR_INTERNAL;
            g_snmp_vbl_free(out);
            return;
        }
        for (row = out, i = 0; row; row = g_slist_next(row), i++) {
            (*ipForwardEntry)[i] = assign_ipForwardEntry(row->data);
        }
    }
}

void
ip_forward_mib_get_ipForwardEntry(GSnmpSession *s, ip_forward_mib_ipForwardEntry_t **ipForwardEntry, guchar *ipForwardDest, gint32 ipForwardProto, gint32 ipForwardPolicy, guchar *ipForwardNextHop, gint mask)
{
    GSList *in = NULL, *out = NULL;
    guint32 base[128];
    gint8 len;

    memset(base, 0, sizeof(base));
    memcpy(base, oid_ipForwardEntry, sizeof(oid_ipForwardEntry));
    len = pack_ipForwardEntry(base, ipForwardDest, ipForwardProto, ipForwardPolicy, ipForwardNextHop);
    if (len < 0) {
        g_warning("illegal ipForwardEntry index values");
        s->error_status = G_SNMP_ERR_INTERNAL;
        return;
    }

    *ipForwardEntry = NULL;

    add_attributes(s, &in, base, len, 10, attr_ipForwardEntry, mask);

    out = g_snmp_session_sync_get(s, in);
    g_snmp_vbl_free(in);
    if (out) {
        if (s->error_status != G_SNMP_ERR_NOERROR) {
            g_snmp_vbl_free(out);
            return;
        }
        *ipForwardEntry = assign_ipForwardEntry(out);
    }
}

void
ip_forward_mib_set_ipForwardEntry(GSnmpSession *s, ip_forward_mib_ipForwardEntry_t *ipForwardEntry, gint mask)
{
    GSList *in = NULL, *out = NULL;
    guint32 base[128];
    gint8 len;

    memset(base, 0, sizeof(base));
    memcpy(base, oid_ipForwardEntry, sizeof(oid_ipForwardEntry));
    len = pack_ipForwardEntry(base, ipForwardEntry->ipForwardDest, ipForwardEntry->ipForwardProto, ipForwardEntry->ipForwardPolicy, ipForwardEntry->ipForwardNextHop);
    if (len < 0) {
        g_warning("illegal ipForwardEntry index values");
        s->error_status = G_SNMP_ERR_INTERNAL;
        return;
    }

    if (ipForwardEntry->ipForwardMask) {
        base[10] = 2;
        g_snmp_vbl_add(&in, base, len, G_SNMP_IPADDRESS,
                       ipForwardEntry->ipForwardMask,
                       4);
    }
    if (ipForwardEntry->ipForwardIfIndex) {
        base[10] = 5;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipForwardEntry->ipForwardIfIndex,
                       0);
    }
    if (ipForwardEntry->ipForwardType) {
        base[10] = 6;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipForwardEntry->ipForwardType,
                       0);
    }
    if (ipForwardEntry->ipForwardInfo) {
        base[10] = 9;
        g_snmp_vbl_add(&in, base, len, G_SNMP_OBJECTID,
                       ipForwardEntry->ipForwardInfo,
                       ipForwardEntry->_ipForwardInfoLength);
    }
    if (ipForwardEntry->ipForwardNextHopAS) {
        base[10] = 10;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipForwardEntry->ipForwardNextHopAS,
                       0);
    }
    if (ipForwardEntry->ipForwardMetric1) {
        base[10] = 11;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipForwardEntry->ipForwardMetric1,
                       0);
    }
    if (ipForwardEntry->ipForwardMetric2) {
        base[10] = 12;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipForwardEntry->ipForwardMetric2,
                       0);
    }
    if (ipForwardEntry->ipForwardMetric3) {
        base[10] = 13;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipForwardEntry->ipForwardMetric3,
                       0);
    }
    if (ipForwardEntry->ipForwardMetric4) {
        base[10] = 14;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipForwardEntry->ipForwardMetric4,
                       0);
    }
    if (ipForwardEntry->ipForwardMetric5) {
        base[10] = 15;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipForwardEntry->ipForwardMetric5,
                       0);
    }

    out = g_snmp_session_sync_set(s, in);
    g_snmp_vbl_free(in);
    if (out) {
        g_snmp_vbl_free(out);
    }
}

void
ip_forward_mib_free_ipForwardEntry(ip_forward_mib_ipForwardEntry_t *ipForwardEntry)
{
    GSList *vbl;
    char *p;

    if (ipForwardEntry) {
        p = (char *) ipForwardEntry + sizeof(ip_forward_mib_ipForwardEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(ipForwardEntry);
    }
}

void
ip_forward_mib_free_ipForwardTable(ip_forward_mib_ipForwardEntry_t **ipForwardEntry)
{
    int i;

    if (ipForwardEntry) {
        for (i = 0; ipForwardEntry[i]; i++) {
            ip_forward_mib_free_ipForwardEntry(ipForwardEntry[i]);
        }
        g_free(ipForwardEntry);
    }
}

ip_forward_mib_ipCidrRouteEntry_t *
ip_forward_mib_new_ipCidrRouteEntry()
{
    ip_forward_mib_ipCidrRouteEntry_t *ipCidrRouteEntry;

    ipCidrRouteEntry = (ip_forward_mib_ipCidrRouteEntry_t *) g_malloc0(sizeof(ip_forward_mib_ipCidrRouteEntry_t) + sizeof(gpointer));
    return ipCidrRouteEntry;
}

static int
unpack_ipCidrRouteEntry(GSnmpVarBind *vb, ip_forward_mib_ipCidrRouteEntry_t *ipCidrRouteEntry)
{
    int idx = 11;
    guint16 i, len;

    len = 4;
    if (vb->id_len < idx + len) return -1;
    if (len != 4) return -1;
    if (vb->id_len < idx + len) return -1;
    for (i = 0; i < len; i++) {
        ipCidrRouteEntry->ipCidrRouteDest[i] = vb->id[idx++];
    }
    len = 4;
    if (vb->id_len < idx + len) return -1;
    if (len != 4) return -1;
    if (vb->id_len < idx + len) return -1;
    for (i = 0; i < len; i++) {
        ipCidrRouteEntry->ipCidrRouteMask[i] = vb->id[idx++];
    }
    if (vb->id_len < idx) return -1;
    ipCidrRouteEntry->ipCidrRouteTos = vb->id[idx++];
    len = 4;
    if (vb->id_len < idx + len) return -1;
    if (len != 4) return -1;
    if (vb->id_len < idx + len) return -1;
    for (i = 0; i < len; i++) {
        ipCidrRouteEntry->ipCidrRouteNextHop[i] = vb->id[idx++];
    }
    if (vb->id_len > idx) return -1;
    return 0;
}

static int
pack_ipCidrRouteEntry(guint32 *base, guchar *ipCidrRouteDest, guchar *ipCidrRouteMask, gint32 ipCidrRouteTos, guchar *ipCidrRouteNextHop)
{
    int idx = 11;
    guint16 i, len;

    len = 4;
    if (len != 4) return -1;
    for (i = 0; i < len; i++) {
        base[idx++] = ipCidrRouteDest[i];
        if (idx >= 128) return -1;
    }
    len = 4;
    if (len != 4) return -1;
    for (i = 0; i < len; i++) {
        base[idx++] = ipCidrRouteMask[i];
        if (idx >= 128) return -1;
    }
    base[idx++] = ipCidrRouteTos;
    len = 4;
    if (len != 4) return -1;
    for (i = 0; i < len; i++) {
        base[idx++] = ipCidrRouteNextHop[i];
        if (idx >= 128) return -1;
    }
    return idx;
}

static ip_forward_mib_ipCidrRouteEntry_t *
assign_ipCidrRouteEntry(GSList *vbl)
{
    GSList *elem;
    ip_forward_mib_ipCidrRouteEntry_t *ipCidrRouteEntry;
    guint32 idx;
    char *p;

    ipCidrRouteEntry = ip_forward_mib_new_ipCidrRouteEntry();
    if (! ipCidrRouteEntry) {
        return NULL;
    }

    p = (char *) ipCidrRouteEntry + sizeof(ip_forward_mib_ipCidrRouteEntry_t);
    * (GSList **) p = vbl;

    if (unpack_ipCidrRouteEntry((GSnmpVarBind *) vbl->data, ipCidrRouteEntry) < 0) {
        g_warning("illegal ipCidrRouteEntry instance identifier");
        g_free(ipCidrRouteEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (lookup(vb, oid_ipCidrRouteEntry, sizeof(oid_ipCidrRouteEntry)/sizeof(guint32),
                   attr_ipCidrRouteEntry, &idx) < 0) continue;

        switch (idx) {
        case 5:
            ipCidrRouteEntry->ipCidrRouteIfIndex = &(vb->syntax.i32[0]);
            break;
        case 6:
            ipCidrRouteEntry->ipCidrRouteType = &(vb->syntax.i32[0]);
            break;
        case 7:
            ipCidrRouteEntry->ipCidrRouteProto = &(vb->syntax.i32[0]);
            break;
        case 8:
            ipCidrRouteEntry->ipCidrRouteAge = &(vb->syntax.i32[0]);
            break;
        case 9:
            if (vb->syntax_len > 128) break;
            ipCidrRouteEntry->_ipCidrRouteInfoLength = vb->syntax_len / sizeof(guint32);
            ipCidrRouteEntry->ipCidrRouteInfo = vb->syntax.ui32;
            break;
        case 10:
            ipCidrRouteEntry->ipCidrRouteNextHopAS = &(vb->syntax.i32[0]);
            break;
        case 11:
            ipCidrRouteEntry->ipCidrRouteMetric1 = &(vb->syntax.i32[0]);
            break;
        case 12:
            ipCidrRouteEntry->ipCidrRouteMetric2 = &(vb->syntax.i32[0]);
            break;
        case 13:
            ipCidrRouteEntry->ipCidrRouteMetric3 = &(vb->syntax.i32[0]);
            break;
        case 14:
            ipCidrRouteEntry->ipCidrRouteMetric4 = &(vb->syntax.i32[0]);
            break;
        case 15:
            ipCidrRouteEntry->ipCidrRouteMetric5 = &(vb->syntax.i32[0]);
            break;
        case 16:
            ipCidrRouteEntry->ipCidrRouteStatus = &(vb->syntax.i32[0]);
            break;
        };
    }

    return ipCidrRouteEntry;
}

void
ip_forward_mib_get_ipCidrRouteTable(GSnmpSession *s, ip_forward_mib_ipCidrRouteEntry_t ***ipCidrRouteEntry, gint mask)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 2, 1, 4, 24, 4, 1, 0};

    *ipCidrRouteEntry = NULL;

    add_attributes(s, &in, base, 11, 10, attr_ipCidrRouteEntry, mask);

    out = gsnmp_gettable(s, in);
    /* g_snmp_vbl_free(in); */

    if (out) {
        *ipCidrRouteEntry = (ip_forward_mib_ipCidrRouteEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(ip_forward_mib_ipCidrRouteEntry_t *));
        if (! *ipCidrRouteEntry) {
            s->error_status = G_SNMP_ERR_INTERNAL;
            g_snmp_vbl_free(out);
            return;
        }
        for (row = out, i = 0; row; row = g_slist_next(row), i++) {
            (*ipCidrRouteEntry)[i] = assign_ipCidrRouteEntry(row->data);
        }
    }
}

void
ip_forward_mib_get_ipCidrRouteEntry(GSnmpSession *s, ip_forward_mib_ipCidrRouteEntry_t **ipCidrRouteEntry, guchar *ipCidrRouteDest, guchar *ipCidrRouteMask, gint32 ipCidrRouteTos, guchar *ipCidrRouteNextHop, gint mask)
{
    GSList *in = NULL, *out = NULL;
    guint32 base[128];
    gint8 len;

    memset(base, 0, sizeof(base));
    memcpy(base, oid_ipCidrRouteEntry, sizeof(oid_ipCidrRouteEntry));
    len = pack_ipCidrRouteEntry(base, ipCidrRouteDest, ipCidrRouteMask, ipCidrRouteTos, ipCidrRouteNextHop);
    if (len < 0) {
        g_warning("illegal ipCidrRouteEntry index values");
        s->error_status = G_SNMP_ERR_INTERNAL;
        return;
    }

    *ipCidrRouteEntry = NULL;

    add_attributes(s, &in, base, len, 10, attr_ipCidrRouteEntry, mask);

    out = g_snmp_session_sync_get(s, in);
    g_snmp_vbl_free(in);
    if (out) {
        if (s->error_status != G_SNMP_ERR_NOERROR) {
            g_snmp_vbl_free(out);
            return;
        }
        *ipCidrRouteEntry = assign_ipCidrRouteEntry(out);
    }
}

void
ip_forward_mib_set_ipCidrRouteEntry(GSnmpSession *s, ip_forward_mib_ipCidrRouteEntry_t *ipCidrRouteEntry, gint mask)
{
    GSList *in = NULL, *out = NULL;
    guint32 base[128];
    gint8 len;

    memset(base, 0, sizeof(base));
    memcpy(base, oid_ipCidrRouteEntry, sizeof(oid_ipCidrRouteEntry));
    len = pack_ipCidrRouteEntry(base, ipCidrRouteEntry->ipCidrRouteDest, ipCidrRouteEntry->ipCidrRouteMask, ipCidrRouteEntry->ipCidrRouteTos, ipCidrRouteEntry->ipCidrRouteNextHop);
    if (len < 0) {
        g_warning("illegal ipCidrRouteEntry index values");
        s->error_status = G_SNMP_ERR_INTERNAL;
        return;
    }

    if (ipCidrRouteEntry->ipCidrRouteIfIndex) {
        base[10] = 5;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipCidrRouteEntry->ipCidrRouteIfIndex,
                       0);
    }
    if (ipCidrRouteEntry->ipCidrRouteType) {
        base[10] = 6;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipCidrRouteEntry->ipCidrRouteType,
                       0);
    }
    if (ipCidrRouteEntry->ipCidrRouteInfo) {
        base[10] = 9;
        g_snmp_vbl_add(&in, base, len, G_SNMP_OBJECTID,
                       ipCidrRouteEntry->ipCidrRouteInfo,
                       ipCidrRouteEntry->_ipCidrRouteInfoLength);
    }
    if (ipCidrRouteEntry->ipCidrRouteNextHopAS) {
        base[10] = 10;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipCidrRouteEntry->ipCidrRouteNextHopAS,
                       0);
    }
    if (ipCidrRouteEntry->ipCidrRouteMetric1) {
        base[10] = 11;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipCidrRouteEntry->ipCidrRouteMetric1,
                       0);
    }
    if (ipCidrRouteEntry->ipCidrRouteMetric2) {
        base[10] = 12;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipCidrRouteEntry->ipCidrRouteMetric2,
                       0);
    }
    if (ipCidrRouteEntry->ipCidrRouteMetric3) {
        base[10] = 13;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipCidrRouteEntry->ipCidrRouteMetric3,
                       0);
    }
    if (ipCidrRouteEntry->ipCidrRouteMetric4) {
        base[10] = 14;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipCidrRouteEntry->ipCidrRouteMetric4,
                       0);
    }
    if (ipCidrRouteEntry->ipCidrRouteMetric5) {
        base[10] = 15;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipCidrRouteEntry->ipCidrRouteMetric5,
                       0);
    }
    if (ipCidrRouteEntry->ipCidrRouteStatus) {
        base[10] = 16;
        g_snmp_vbl_add(&in, base, len, G_SNMP_INTEGER32,
                       ipCidrRouteEntry->ipCidrRouteStatus,
                       0);
    }

    out = g_snmp_session_sync_set(s, in);
    g_snmp_vbl_free(in);
    if (out) {
        g_snmp_vbl_free(out);
    }
}

void
ip_forward_mib_free_ipCidrRouteEntry(ip_forward_mib_ipCidrRouteEntry_t *ipCidrRouteEntry)
{
    GSList *vbl;
    char *p;

    if (ipCidrRouteEntry) {
        p = (char *) ipCidrRouteEntry + sizeof(ip_forward_mib_ipCidrRouteEntry_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(ipCidrRouteEntry);
    }
}

void
ip_forward_mib_free_ipCidrRouteTable(ip_forward_mib_ipCidrRouteEntry_t **ipCidrRouteEntry)
{
    int i;

    if (ipCidrRouteEntry) {
        for (i = 0; ipCidrRouteEntry[i]; i++) {
            ip_forward_mib_free_ipCidrRouteEntry(ipCidrRouteEntry[i]);
        }
        g_free(ipCidrRouteEntry);
    }
}


