/*							-- DO NOT EDIT --
 * This file has been generated by smidump
 * version 0.2.17 for the scli package.
 *
 * Derived from OLD-CISCO-IP-MIB:
 *
 * $Id$
 */

#ifndef _OLD_CISCO_IP_MIB_H_
#define _OLD_CISCO_IP_MIB_H_

#include "g_snmp.h"

/*
 * C type definitions for OLD-CISCO-IP-MIB::lip.
 */

typedef struct {
    gint32   *actThresh;
    gint32   *actLostPkts;
    gint32   *actLostByts;
    guint32  *actAge;
    guint32  *ckactAge;
    gint32   *actCheckPoint;
    guint32  *ipNoaccess;
} old_cisco_ip_mib_lip_t;

extern old_cisco_ip_mib_lip_t *
old_cisco_ip_mib_new_lip();

extern int
old_cisco_ip_mib_get_lip(GSnmpSession *s, old_cisco_ip_mib_lip_t **lip);

extern int
old_cisco_ip_mib_set_lip(GSnmpSession *s, old_cisco_ip_mib_lip_t *lip);

extern void
old_cisco_ip_mib_free_lip(old_cisco_ip_mib_lip_t *lip);

/*
 * C type definitions for OLD-CISCO-IP-MIB::lipAddrEntry.
 */

typedef struct {
    guchar   ipAdEntAddr[4];
    guchar   *locIPHow;
    gsize    _locIPHowLength;
    guchar   *locIPWho;
    guchar   *locIPHelper;
    gint32   *locIPSecurity;
    gint32   *locIPRedirects;
    gint32   *locIPUnreach;
} old_cisco_ip_mib_lipAddrEntry_t;

extern int
old_cisco_ip_mib_get_lipAddrTable(GSnmpSession *s, old_cisco_ip_mib_lipAddrEntry_t ***lipAddrEntry);

extern void
old_cisco_ip_mib_free_lipAddrTable(old_cisco_ip_mib_lipAddrEntry_t **lipAddrEntry);

extern old_cisco_ip_mib_lipAddrEntry_t *
old_cisco_ip_mib_new_lipAddrEntry();

extern int
old_cisco_ip_mib_get_lipAddrEntry(GSnmpSession *s, old_cisco_ip_mib_lipAddrEntry_t **lipAddrEntry);

extern void
old_cisco_ip_mib_free_lipAddrEntry(old_cisco_ip_mib_lipAddrEntry_t *lipAddrEntry);

/*
 * C type definitions for OLD-CISCO-IP-MIB::lipRouteEntry.
 */

typedef struct {
    guchar   ipRouteDest[4];
    guchar   *locRtMask;
    gint32   *locRtCount;
    gint32   *locRtUses;
} old_cisco_ip_mib_lipRouteEntry_t;

extern int
old_cisco_ip_mib_get_lipRouteTable(GSnmpSession *s, old_cisco_ip_mib_lipRouteEntry_t ***lipRouteEntry);

extern void
old_cisco_ip_mib_free_lipRouteTable(old_cisco_ip_mib_lipRouteEntry_t **lipRouteEntry);

extern old_cisco_ip_mib_lipRouteEntry_t *
old_cisco_ip_mib_new_lipRouteEntry();

extern int
old_cisco_ip_mib_get_lipRouteEntry(GSnmpSession *s, old_cisco_ip_mib_lipRouteEntry_t **lipRouteEntry);

extern void
old_cisco_ip_mib_free_lipRouteEntry(old_cisco_ip_mib_lipRouteEntry_t *lipRouteEntry);

/*
 * C type definitions for OLD-CISCO-IP-MIB::lipAccountEntry.
 */

typedef struct {
    guchar   actSrc[4];
    guchar   actDst[4];
    gint32   *actPkts;
    gint32   *actByts;
    gint32   *actViolation;
} old_cisco_ip_mib_lipAccountEntry_t;

extern int
old_cisco_ip_mib_get_lipAccountingTable(GSnmpSession *s, old_cisco_ip_mib_lipAccountEntry_t ***lipAccountEntry);

extern void
old_cisco_ip_mib_free_lipAccountingTable(old_cisco_ip_mib_lipAccountEntry_t **lipAccountEntry);

extern old_cisco_ip_mib_lipAccountEntry_t *
old_cisco_ip_mib_new_lipAccountEntry();

extern int
old_cisco_ip_mib_get_lipAccountEntry(GSnmpSession *s, old_cisco_ip_mib_lipAccountEntry_t **lipAccountEntry);

extern void
old_cisco_ip_mib_free_lipAccountEntry(old_cisco_ip_mib_lipAccountEntry_t *lipAccountEntry);

/*
 * C type definitions for OLD-CISCO-IP-MIB::lipCkAccountEntry.
 */

typedef struct {
    guchar   ckactSrc[4];
    guchar   ckactDst[4];
    gint32   *ckactPkts;
    gint32   *ckactByts;
    gint32   *ckactViolation;
} old_cisco_ip_mib_lipCkAccountEntry_t;

extern int
old_cisco_ip_mib_get_lipCkAccountingTable(GSnmpSession *s, old_cisco_ip_mib_lipCkAccountEntry_t ***lipCkAccountEntry);

extern void
old_cisco_ip_mib_free_lipCkAccountingTable(old_cisco_ip_mib_lipCkAccountEntry_t **lipCkAccountEntry);

extern old_cisco_ip_mib_lipCkAccountEntry_t *
old_cisco_ip_mib_new_lipCkAccountEntry();

extern int
old_cisco_ip_mib_get_lipCkAccountEntry(GSnmpSession *s, old_cisco_ip_mib_lipCkAccountEntry_t **lipCkAccountEntry);

extern void
old_cisco_ip_mib_free_lipCkAccountEntry(old_cisco_ip_mib_lipCkAccountEntry_t *lipCkAccountEntry);


#endif /* _OLD_CISCO_IP_MIB_H_ */
