/*							-- DO NOT EDIT --
 * This file has been generated by smidump
 * version 0.2.14 for the stools package.
 *
 * Derived from SNMP-FRAMEWORK-MIB:
 *   The SNMP Management Architecture MIB
 *
 * Revision 1999-01-19 00:00:
 *   Updated editors' addresses, fixed typos.
 *   Published as RFC2571.
 *   
 *
 * Revision 1997-11-20 00:00:
 *   The initial version, published in RFC 2271.
 *   
 *
 * $Id$
 */

#include "snmp-framework-mib.h"

static guint32 const snmpAuthProtocols[]
	= { SNMP_FRAMEWORK_MIB_SNMPAUTHPROTOCOLS };
static guint32 const snmpPrivProtocols[]
	= { SNMP_FRAMEWORK_MIB_SNMPPRIVPROTOCOLS };

stls_identity_t const snmp_framework_mib_identities[] = {
    { snmpAuthProtocols,
      sizeof(snmpAuthProtocols)/sizeof(guint32),
      "snmpAuthProtocols" },
    { snmpPrivProtocols,
      sizeof(snmpPrivProtocols)/sizeof(guint32),
      "snmpPrivProtocols" },
    { 0, 0, NULL }
};


static stls_stub_attr_t _snmpEngine[] = {
    { 1, G_SNMP_OCTET_STRING, "snmpEngineID" },
    { 2, G_SNMP_INTEGER32, "snmpEngineBoots" },
    { 3, G_SNMP_INTEGER32, "snmpEngineTime" },
    { 4, G_SNMP_INTEGER32, "snmpEngineMaxMessageSize" },
    { 0, 0, NULL }
};


snmp_framework_mib_snmpEngine_t *
snmp_framework_mib_new_snmpEngine()
{
    snmp_framework_mib_snmpEngine_t *snmpEngine;

    snmpEngine = (snmp_framework_mib_snmpEngine_t *) g_malloc0(sizeof(snmp_framework_mib_snmpEngine_t) + sizeof(gpointer));
    return snmpEngine;
}

static snmp_framework_mib_snmpEngine_t *
assign_snmpEngine(GSList *vbl)
{
    GSList *elem;
    snmp_framework_mib_snmpEngine_t *snmpEngine;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 6, 3, 10, 2, 1};

    snmpEngine = snmp_framework_mib_new_snmpEngine();
    if (! snmpEngine) {
        return NULL;
    }

    p = (char *) snmpEngine + sizeof(snmp_framework_mib_snmpEngine_t);
    * (GSList **) p = vbl;

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (stls_vb_lookup(vb, base, sizeof(base)/sizeof(guint32),
                           _snmpEngine, &idx) < 0) continue;

        switch (idx) {
        case 1:
            snmpEngine->_snmpEngineIDLength = vb->syntax_len;
            snmpEngine->snmpEngineID = vb->syntax.uc;
            break;
        case 2:
            snmpEngine->snmpEngineBoots = &(vb->syntax.i32[0]);
            break;
        case 3:
            snmpEngine->snmpEngineTime = &(vb->syntax.i32[0]);
            break;
        case 4:
            snmpEngine->snmpEngineMaxMessageSize = &(vb->syntax.i32[0]);
            break;
        };
    }

    return snmpEngine;
}

int
snmp_framework_mib_get_snmpEngine(GSnmpSession *s, snmp_framework_mib_snmpEngine_t **snmpEngine)
{
    GSList *in = NULL, *out = NULL;
    static guint32 base[] = {1, 3, 6, 1, 6, 3, 10, 2, 1, 0};

    *snmpEngine = NULL;

    stls_vbl_attributes(s, &in, base, 9, _snmpEngine);

    out = g_snmp_session_sync_getnext(s, in);
    g_snmp_vbl_free(in);
    if (! out) {
        return -2;
    }

    *snmpEngine = assign_snmpEngine(out);

    return 0;
}

void
snmp_framework_mib_free_snmpEngine(snmp_framework_mib_snmpEngine_t *snmpEngine)
{
    GSList *vbl;
    char *p;

    if (snmpEngine) {
        p = (char *) snmpEngine + sizeof(snmp_framework_mib_snmpEngine_t);
        vbl = * (GSList **) p;
        g_snmp_vbl_free(vbl);
        g_free(snmpEngine);
    }
}


