/*							-- DO NOT EDIT --
 * This file has been generated by smidump
 * version 0.2.14 for the stools package.
 *
 * Derived from SNMP-TARGET-MIB:
 *   This MIB module defines MIB objects which provide
 *   mechanisms to remotely configure the parameters used
 *   by an SNMP entity for the generation of SNMP messages.
 *
 * Revision 1998-08-04 00:00:
 *   Clarifications, published as
 *   RFC2573.
 *
 * Revision 1997-07-14 00:00:
 *   The initial revision, published as RFC2273.
 *
 * $Id$
 */

#include "snmp-target-mib.h"

stls_enum_t const snmp_target_mib_enums_snmpTargetAddrStorageType[] = {
    { SNMP_TARGET_MIB_SNMPTARGETADDRSTORAGETYPE_OTHER,	"other" },
    { SNMP_TARGET_MIB_SNMPTARGETADDRSTORAGETYPE_VOLATILE,	"volatile" },
    { SNMP_TARGET_MIB_SNMPTARGETADDRSTORAGETYPE_NONVOLATILE,	"nonVolatile" },
    { SNMP_TARGET_MIB_SNMPTARGETADDRSTORAGETYPE_PERMANENT,	"permanent" },
    { SNMP_TARGET_MIB_SNMPTARGETADDRSTORAGETYPE_READONLY,	"readOnly" },
    { 0, NULL }
};

stls_enum_t const snmp_target_mib_enums_snmpTargetAddrRowStatus[] = {
    { SNMP_TARGET_MIB_SNMPTARGETADDRROWSTATUS_ACTIVE,	"active" },
    { SNMP_TARGET_MIB_SNMPTARGETADDRROWSTATUS_NOTINSERVICE,	"notInService" },
    { SNMP_TARGET_MIB_SNMPTARGETADDRROWSTATUS_NOTREADY,	"notReady" },
    { SNMP_TARGET_MIB_SNMPTARGETADDRROWSTATUS_CREATEANDGO,	"createAndGo" },
    { SNMP_TARGET_MIB_SNMPTARGETADDRROWSTATUS_CREATEANDWAIT,	"createAndWait" },
    { SNMP_TARGET_MIB_SNMPTARGETADDRROWSTATUS_DESTROY,	"destroy" },
    { 0, NULL }
};

stls_enum_t const snmp_target_mib_enums_snmpTargetParamsSecurityLevel[] = {
    { SNMP_TARGET_MIB_SNMPTARGETPARAMSSECURITYLEVEL_NOAUTHNOPRIV,	"noAuthNoPriv" },
    { SNMP_TARGET_MIB_SNMPTARGETPARAMSSECURITYLEVEL_AUTHNOPRIV,	"authNoPriv" },
    { SNMP_TARGET_MIB_SNMPTARGETPARAMSSECURITYLEVEL_AUTHPRIV,	"authPriv" },
    { 0, NULL }
};

stls_enum_t const snmp_target_mib_enums_snmpTargetParamsStorageType[] = {
    { SNMP_TARGET_MIB_SNMPTARGETPARAMSSTORAGETYPE_OTHER,	"other" },
    { SNMP_TARGET_MIB_SNMPTARGETPARAMSSTORAGETYPE_VOLATILE,	"volatile" },
    { SNMP_TARGET_MIB_SNMPTARGETPARAMSSTORAGETYPE_NONVOLATILE,	"nonVolatile" },
    { SNMP_TARGET_MIB_SNMPTARGETPARAMSSTORAGETYPE_PERMANENT,	"permanent" },
    { SNMP_TARGET_MIB_SNMPTARGETPARAMSSTORAGETYPE_READONLY,	"readOnly" },
    { 0, NULL }
};

stls_enum_t const snmp_target_mib_enums_snmpTargetParamsRowStatus[] = {
    { SNMP_TARGET_MIB_SNMPTARGETPARAMSROWSTATUS_ACTIVE,	"active" },
    { SNMP_TARGET_MIB_SNMPTARGETPARAMSROWSTATUS_NOTINSERVICE,	"notInService" },
    { SNMP_TARGET_MIB_SNMPTARGETPARAMSROWSTATUS_NOTREADY,	"notReady" },
    { SNMP_TARGET_MIB_SNMPTARGETPARAMSROWSTATUS_CREATEANDGO,	"createAndGo" },
    { SNMP_TARGET_MIB_SNMPTARGETPARAMSROWSTATUS_CREATEANDWAIT,	"createAndWait" },
    { SNMP_TARGET_MIB_SNMPTARGETPARAMSROWSTATUS_DESTROY,	"destroy" },
    { 0, NULL }
};


static stls_stub_attr_t _snmpTargetObjects[] = {
    { 1, G_SNMP_INTEGER32, "snmpTargetSpinLock" },
    { 4, G_SNMP_COUNTER32, "snmpUnavailableContexts" },
    { 5, G_SNMP_COUNTER32, "snmpUnknownContexts" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _snmpTargetAddrEntry[] = {
    { 2, G_SNMP_OBJECT_ID, "snmpTargetAddrTDomain" },
    { 3, G_SNMP_OCTET_STRING, "snmpTargetAddrTAddress" },
    { 4, G_SNMP_INTEGER32, "snmpTargetAddrTimeout" },
    { 5, G_SNMP_INTEGER32, "snmpTargetAddrRetryCount" },
    { 6, G_SNMP_OCTET_STRING, "snmpTargetAddrTagList" },
    { 7, G_SNMP_OCTET_STRING, "snmpTargetAddrParams" },
    { 8, G_SNMP_INTEGER32, "snmpTargetAddrStorageType" },
    { 9, G_SNMP_INTEGER32, "snmpTargetAddrRowStatus" },
    { 0, 0, NULL }
};

static stls_stub_attr_t _snmpTargetParamsEntry[] = {
    { 2, G_SNMP_INTEGER32, "snmpTargetParamsMPModel" },
    { 3, G_SNMP_INTEGER32, "snmpTargetParamsSecurityModel" },
    { 4, G_SNMP_OCTET_STRING, "snmpTargetParamsSecurityName" },
    { 5, G_SNMP_INTEGER32, "snmpTargetParamsSecurityLevel" },
    { 6, G_SNMP_INTEGER32, "snmpTargetParamsStorageType" },
    { 7, G_SNMP_INTEGER32, "snmpTargetParamsRowStatus" },
    { 0, 0, NULL }
};


snmp_target_mib_snmpTargetObjects_t *
snmp_target_mib_new_snmpTargetObjects()
{
    snmp_target_mib_snmpTargetObjects_t *snmpTargetObjects;

    snmpTargetObjects = (snmp_target_mib_snmpTargetObjects_t *) g_malloc0(sizeof(snmp_target_mib_snmpTargetObjects_t) + sizeof(gpointer));
    return snmpTargetObjects;
}

static snmp_target_mib_snmpTargetObjects_t *
assign_snmpTargetObjects(GSList *vbl)
{
    GSList *elem;
    snmp_target_mib_snmpTargetObjects_t *snmpTargetObjects;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 6, 3, 12, 1};

    snmpTargetObjects = snmp_target_mib_new_snmpTargetObjects();
    if (! snmpTargetObjects) {
        return NULL;
    }

    p = (char *) snmpTargetObjects + sizeof(snmp_target_mib_snmpTargetObjects_t);
    * (GSList **) p = vbl;

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (stls_vb_lookup(vb, base, sizeof(base)/sizeof(guint32),
                           _snmpTargetObjects, &idx) < 0) continue;

        switch (idx) {
        case 1:
            snmpTargetObjects->snmpTargetSpinLock = &(vb->syntax.i32[0]);
            break;
        case 4:
            snmpTargetObjects->snmpUnavailableContexts = &(vb->syntax.ui32[0]);
            break;
        case 5:
            snmpTargetObjects->snmpUnknownContexts = &(vb->syntax.ui32[0]);
            break;
        };
    }

    return snmpTargetObjects;
}

int
snmp_target_mib_get_snmpTargetObjects(host_snmp *s, snmp_target_mib_snmpTargetObjects_t **snmpTargetObjects)
{
    GSList *in = NULL, *out = NULL;
    static guint32 base[] = {1, 3, 6, 1, 6, 3, 12, 1, 0};

    *snmpTargetObjects = NULL;

    stls_vbl_attributes(s, &in, base, 8, _snmpTargetObjects);

    out = stls_snmp_getnext(s, in);
    stls_vbl_free(in);
    if (! out) {
        return -2;
    }

    *snmpTargetObjects = assign_snmpTargetObjects(out);

    return 0;
}

void
snmp_target_mib_free_snmpTargetObjects(snmp_target_mib_snmpTargetObjects_t *snmpTargetObjects)
{
    GSList *vbl;
    char *p;

    if (snmpTargetObjects) {
        p = (char *) snmpTargetObjects + sizeof(snmp_target_mib_snmpTargetObjects_t);
        vbl = * (GSList **) p;
        stls_vbl_free(vbl);
        g_free(snmpTargetObjects);
    }
}

snmp_target_mib_snmpTargetAddrEntry_t *
snmp_target_mib_new_snmpTargetAddrEntry()
{
    snmp_target_mib_snmpTargetAddrEntry_t *snmpTargetAddrEntry;

    snmpTargetAddrEntry = (snmp_target_mib_snmpTargetAddrEntry_t *) g_malloc0(sizeof(snmp_target_mib_snmpTargetAddrEntry_t) + sizeof(gpointer));
    return snmpTargetAddrEntry;
}

static int
unpack_snmpTargetAddrEntry(GSnmpVarBind *vb, snmp_target_mib_snmpTargetAddrEntry_t *snmpTargetAddrEntry)
{
    int i, len, idx = 11;

    if (vb->id_len < idx) return -1;
    len = vb->id_len - idx;
    for (i = 0; i < len; i++) {
        snmpTargetAddrEntry->snmpTargetAddrName[i] = vb->id[idx++];
    }
    snmpTargetAddrEntry->_snmpTargetAddrNameLength = len;
    if (vb->id_len > idx) return -1;
    return 0;
}

static snmp_target_mib_snmpTargetAddrEntry_t *
assign_snmpTargetAddrEntry(GSList *vbl)
{
    GSList *elem;
    snmp_target_mib_snmpTargetAddrEntry_t *snmpTargetAddrEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 6, 3, 12, 1, 2, 1};

    snmpTargetAddrEntry = snmp_target_mib_new_snmpTargetAddrEntry();
    if (! snmpTargetAddrEntry) {
        return NULL;
    }

    p = (char *) snmpTargetAddrEntry + sizeof(snmp_target_mib_snmpTargetAddrEntry_t);
    * (GSList **) p = vbl;

    if (unpack_snmpTargetAddrEntry((GSnmpVarBind *) vbl->data, snmpTargetAddrEntry) < 0) {
        g_warning("illegal snmpTargetAddrEntry instance identifier");
        g_free(snmpTargetAddrEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (stls_vb_lookup(vb, base, sizeof(base)/sizeof(guint32),
                           _snmpTargetAddrEntry, &idx) < 0) continue;

        switch (idx) {
        case 2:
            snmpTargetAddrEntry->_snmpTargetAddrTDomainLength = vb->syntax_len / sizeof(guint32);
            snmpTargetAddrEntry->snmpTargetAddrTDomain = vb->syntax.ui32;
            break;
        case 3:
            snmpTargetAddrEntry->_snmpTargetAddrTAddressLength = vb->syntax_len;
            snmpTargetAddrEntry->snmpTargetAddrTAddress = vb->syntax.uc;
            break;
        case 4:
            snmpTargetAddrEntry->snmpTargetAddrTimeout = &(vb->syntax.i32[0]);
            break;
        case 5:
            snmpTargetAddrEntry->snmpTargetAddrRetryCount = &(vb->syntax.i32[0]);
            break;
        case 6:
            snmpTargetAddrEntry->_snmpTargetAddrTagListLength = vb->syntax_len;
            snmpTargetAddrEntry->snmpTargetAddrTagList = vb->syntax.uc;
            break;
        case 7:
            snmpTargetAddrEntry->_snmpTargetAddrParamsLength = vb->syntax_len;
            snmpTargetAddrEntry->snmpTargetAddrParams = vb->syntax.uc;
            break;
        case 8:
            snmpTargetAddrEntry->snmpTargetAddrStorageType = &(vb->syntax.i32[0]);
            break;
        case 9:
            snmpTargetAddrEntry->snmpTargetAddrRowStatus = &(vb->syntax.i32[0]);
            break;
        };
    }

    return snmpTargetAddrEntry;
}

int
snmp_target_mib_get_snmpTargetAddrTable(host_snmp *s, snmp_target_mib_snmpTargetAddrEntry_t ***snmpTargetAddrEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 6, 3, 12, 1, 2, 1, 0};

    *snmpTargetAddrEntry = NULL;

    stls_vbl_attributes(s, &in, base, 10, _snmpTargetAddrEntry);

    out = stls_snmp_gettable(s, in);
    /* stls_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *snmpTargetAddrEntry = (snmp_target_mib_snmpTargetAddrEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(snmp_target_mib_snmpTargetAddrEntry_t *));
    if (! *snmpTargetAddrEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*snmpTargetAddrEntry)[i] = assign_snmpTargetAddrEntry(row->data);
    }

    return 0;
}

void
snmp_target_mib_free_snmpTargetAddrEntry(snmp_target_mib_snmpTargetAddrEntry_t *snmpTargetAddrEntry)
{
    GSList *vbl;
    char *p;

    if (snmpTargetAddrEntry) {
        p = (char *) snmpTargetAddrEntry + sizeof(snmp_target_mib_snmpTargetAddrEntry_t);
        vbl = * (GSList **) p;
        stls_vbl_free(vbl);
        g_free(snmpTargetAddrEntry);
    }
}

void
snmp_target_mib_free_snmpTargetAddrTable(snmp_target_mib_snmpTargetAddrEntry_t **snmpTargetAddrEntry)
{
    int i;

    if (snmpTargetAddrEntry) {
        for (i = 0; snmpTargetAddrEntry[i]; i++) {
            snmp_target_mib_free_snmpTargetAddrEntry(snmpTargetAddrEntry[i]);
        }
        g_free(snmpTargetAddrEntry);
    }
}

snmp_target_mib_snmpTargetParamsEntry_t *
snmp_target_mib_new_snmpTargetParamsEntry()
{
    snmp_target_mib_snmpTargetParamsEntry_t *snmpTargetParamsEntry;

    snmpTargetParamsEntry = (snmp_target_mib_snmpTargetParamsEntry_t *) g_malloc0(sizeof(snmp_target_mib_snmpTargetParamsEntry_t) + sizeof(gpointer));
    return snmpTargetParamsEntry;
}

static int
unpack_snmpTargetParamsEntry(GSnmpVarBind *vb, snmp_target_mib_snmpTargetParamsEntry_t *snmpTargetParamsEntry)
{
    int i, len, idx = 11;

    if (vb->id_len < idx) return -1;
    len = vb->id_len - idx;
    for (i = 0; i < len; i++) {
        snmpTargetParamsEntry->snmpTargetParamsName[i] = vb->id[idx++];
    }
    snmpTargetParamsEntry->_snmpTargetParamsNameLength = len;
    if (vb->id_len > idx) return -1;
    return 0;
}

static snmp_target_mib_snmpTargetParamsEntry_t *
assign_snmpTargetParamsEntry(GSList *vbl)
{
    GSList *elem;
    snmp_target_mib_snmpTargetParamsEntry_t *snmpTargetParamsEntry;
    guint32 idx;
    char *p;
    static guint32 const base[] = {1, 3, 6, 1, 6, 3, 12, 1, 3, 1};

    snmpTargetParamsEntry = snmp_target_mib_new_snmpTargetParamsEntry();
    if (! snmpTargetParamsEntry) {
        return NULL;
    }

    p = (char *) snmpTargetParamsEntry + sizeof(snmp_target_mib_snmpTargetParamsEntry_t);
    * (GSList **) p = vbl;

    if (unpack_snmpTargetParamsEntry((GSnmpVarBind *) vbl->data, snmpTargetParamsEntry) < 0) {
        g_warning("illegal snmpTargetParamsEntry instance identifier");
        g_free(snmpTargetParamsEntry);
        return NULL;
    }

    for (elem = vbl; elem; elem = g_slist_next(elem)) {
        GSnmpVarBind *vb = (GSnmpVarBind *) elem->data;

        if (stls_vb_lookup(vb, base, sizeof(base)/sizeof(guint32),
                           _snmpTargetParamsEntry, &idx) < 0) continue;

        switch (idx) {
        case 2:
            snmpTargetParamsEntry->snmpTargetParamsMPModel = &(vb->syntax.i32[0]);
            break;
        case 3:
            snmpTargetParamsEntry->snmpTargetParamsSecurityModel = &(vb->syntax.i32[0]);
            break;
        case 4:
            snmpTargetParamsEntry->_snmpTargetParamsSecurityNameLength = vb->syntax_len;
            snmpTargetParamsEntry->snmpTargetParamsSecurityName = vb->syntax.uc;
            break;
        case 5:
            snmpTargetParamsEntry->snmpTargetParamsSecurityLevel = &(vb->syntax.i32[0]);
            break;
        case 6:
            snmpTargetParamsEntry->snmpTargetParamsStorageType = &(vb->syntax.i32[0]);
            break;
        case 7:
            snmpTargetParamsEntry->snmpTargetParamsRowStatus = &(vb->syntax.i32[0]);
            break;
        };
    }

    return snmpTargetParamsEntry;
}

int
snmp_target_mib_get_snmpTargetParamsTable(host_snmp *s, snmp_target_mib_snmpTargetParamsEntry_t ***snmpTargetParamsEntry)
{
    GSList *in = NULL, *out = NULL;
    GSList *row;
    int i;
    static guint32 base[] = {1, 3, 6, 1, 6, 3, 12, 1, 3, 1, 0};

    *snmpTargetParamsEntry = NULL;

    stls_vbl_attributes(s, &in, base, 10, _snmpTargetParamsEntry);

    out = stls_snmp_gettable(s, in);
    /* stls_vbl_free(in); */
    if (! out) {
        return -2;
    }

    *snmpTargetParamsEntry = (snmp_target_mib_snmpTargetParamsEntry_t **) g_malloc0((g_slist_length(out) + 1) * sizeof(snmp_target_mib_snmpTargetParamsEntry_t *));
    if (! *snmpTargetParamsEntry) {
        return -4;
    }

    for (row = out, i = 0; row; row = g_slist_next(row), i++) {
        (*snmpTargetParamsEntry)[i] = assign_snmpTargetParamsEntry(row->data);
    }

    return 0;
}

void
snmp_target_mib_free_snmpTargetParamsEntry(snmp_target_mib_snmpTargetParamsEntry_t *snmpTargetParamsEntry)
{
    GSList *vbl;
    char *p;

    if (snmpTargetParamsEntry) {
        p = (char *) snmpTargetParamsEntry + sizeof(snmp_target_mib_snmpTargetParamsEntry_t);
        vbl = * (GSList **) p;
        stls_vbl_free(vbl);
        g_free(snmpTargetParamsEntry);
    }
}

void
snmp_target_mib_free_snmpTargetParamsTable(snmp_target_mib_snmpTargetParamsEntry_t **snmpTargetParamsEntry)
{
    int i;

    if (snmpTargetParamsEntry) {
        for (i = 0; snmpTargetParamsEntry[i]; i++) {
            snmp_target_mib_free_snmpTargetParamsEntry(snmpTargetParamsEntry[i]);
        }
        g_free(snmpTargetParamsEntry);
    }
}


