/*							-- DO NOT EDIT --
 * This file has been generated by smidump
 * version 0.2.13 for the stools package.
 *
 * Derived from SNMPv2-MIB revision 1995-11-09 00:00.
 *
 * $Id$
 */

#ifndef _SNMPV2_MIB_H_
#define _SNMPV2_MIB_H_

#include "stools.h"

/*
 * Tables to map enumerations to strings and vice versa.
 */

extern stls_table_t snmpv2_mib_enums_snmpEnableAuthenTraps[];

/*
 * C type definitions for SNMPv2-MIB::system.
 */

typedef struct system {
    guchar   *sysDescr;
    gsize    _sysDescrLength;
    guint32  *sysObjectID;
    gsize    _sysObjectIDLength;
    guint32  *sysUpTime;
    guchar   *sysContact;
    gsize    _sysContactLength;
    guchar   *sysName;
    gsize    _sysNameLength;
    guchar   *sysLocation;
    gsize    _sysLocationLength;
    gint32   *sysServices;
    guint32  *sysORLastChange;
} system_t;

extern int
snmpv2_mib_get_system(host_snmp *s, system_t **system);

extern void
snmpv2_mib_free_system(system_t *system);

/*
 * C type definitions for SNMPv2-MIB::sysOREntry.
 */

typedef struct sysOREntry {
    gint32   *sysORIndex;
    guint32  *sysORID;
    gsize    _sysORIDLength;
    guchar   *sysORDescr;
    gsize    _sysORDescrLength;
    guint32  *sysORUpTime;
} sysOREntry_t;

extern int
snmpv2_mib_get_sysOREntry(host_snmp *s, sysOREntry_t ***sysOREntry);

extern void
snmpv2_mib_free_sysOREntry(sysOREntry_t **sysOREntry);

/*
 * C type definitions for SNMPv2-MIB::snmp.
 */

typedef struct snmp {
    guint32  *snmpInPkts;
    guint32  *snmpOutPkts;
    guint32  *snmpInBadVersions;
    guint32  *snmpInBadCommunityNames;
    guint32  *snmpInBadCommunityUses;
    guint32  *snmpInASNParseErrs;
    guint32  *snmpInTooBigs;
    guint32  *snmpInNoSuchNames;
    guint32  *snmpInBadValues;
    guint32  *snmpInReadOnlys;
    guint32  *snmpInGenErrs;
    guint32  *snmpInTotalReqVars;
    guint32  *snmpInTotalSetVars;
    guint32  *snmpInGetRequests;
    guint32  *snmpInGetNexts;
    guint32  *snmpInSetRequests;
    guint32  *snmpInGetResponses;
    guint32  *snmpInTraps;
    guint32  *snmpOutTooBigs;
    guint32  *snmpOutNoSuchNames;
    guint32  *snmpOutBadValues;
    guint32  *snmpOutGenErrs;
    guint32  *snmpOutGetRequests;
    guint32  *snmpOutGetNexts;
    guint32  *snmpOutSetRequests;
    guint32  *snmpOutGetResponses;
    guint32  *snmpOutTraps;
    gint32   *snmpEnableAuthenTraps;
    guint32  *snmpSilentDrops;
    guint32  *snmpProxyDrops;
} snmp_t;

extern int
snmpv2_mib_get_snmp(host_snmp *s, snmp_t **snmp);

extern void
snmpv2_mib_free_snmp(snmp_t *snmp);

/*
 * C type definitions for SNMPv2-MIB::snmpSet.
 */

typedef struct snmpSet {
    gint32   *snmpSetSerialNo;
} snmpSet_t;

extern int
snmpv2_mib_get_snmpSet(host_snmp *s, snmpSet_t **snmpSet);

extern void
snmpv2_mib_free_snmpSet(snmpSet_t *snmpSet);


#endif /* _SNMPV2_MIB_H_ */
